/**
 * Declarative Component Factory Registry (40+ NextGen Windows Forms & Avalonia Components)
 * Defines specifications, default sizes, properties, C# types, and Avalonia XAML tags.
 */

import { ControlType } from '../types/ast';

export interface ControlMetadata {
  type: ControlType;
  category: 'Common' | 'Containers' | 'Menus' | 'Advanced' | 'Data';
  displayName: string;
  icon: string;
  defaultSize: { width: number; height: number };
  defaultProps: Record<string, any>;
  isContainer: boolean; // Может ли принимать другие контролы внутрь
  csharpType: string;
  xamlTag: string;
  description: string;
}

export const COMPONENT_REGISTRY: Record<string, ControlMetadata> = {
  // 1. Кнопки и тумблеры
  Button: {
    type: 'Button',
    category: 'Common',
    displayName: 'Кнопка (Button)',
    icon: '🔘',
    defaultSize: { width: 120, height: 35 },
    defaultProps: { text: 'Кнопка', backColor: '#2563EB', foreColor: '#FFFFFF', enabled: true, visible: true },
    isContainer: false,
    csharpType: 'System.Windows.Forms.Button',
    xamlTag: 'Button',
    description: 'Интерактивная кнопка для выполнения команд и вызова событий Click',
  },
  ToggleSwitch: {
    type: 'ToggleSwitch',
    category: 'Common',
    displayName: 'ToggleSwitch (iOS)',
    icon: '🔘',
    defaultSize: { width: 50, height: 26 },
    defaultProps: { checked: false, text: '', enabled: true, visible: true },
    isContainer: false,
    csharpType: 'System.Windows.Forms.ToggleSwitch',
    xamlTag: 'ToggleSwitch',
    description: 'Современный тумблер включения/выключения в стиле iOS',
  },
  CheckBox: {
    type: 'CheckBox',
    category: 'Common',
    displayName: 'Флажок (CheckBox)',
    icon: '☑️',
    defaultSize: { width: 130, height: 24 },
    defaultProps: { text: 'Флажок', checked: false, enabled: true, visible: true },
    isContainer: false,
    csharpType: 'System.Windows.Forms.CheckBox',
    xamlTag: 'CheckBox',
    description: 'Флажок с логическим состоянием (включено / выключено)',
  },
  RadioButton: {
    type: 'RadioButton',
    category: 'Common',
    displayName: 'Переключатель (RadioButton)',
    icon: '🔘',
    defaultSize: { width: 130, height: 24 },
    defaultProps: { text: 'Опция', checked: false, enabled: true, visible: true },
    isContainer: false,
    csharpType: 'System.Windows.Forms.RadioButton',
    xamlTag: 'RadioButton',
    description: 'Круглый переключатель для выбора единственного значения из группы',
  },
  IconButton: {
    type: 'IconButton',
    category: 'Common',
    displayName: 'Кнопка с иконкой (IconButton)',
    icon: '🔘',
    defaultSize: { width: 100, height: 35 },
    defaultProps: { text: 'Поиск', iconName: 'search', enabled: true, visible: true },
    isContainer: false,
    csharpType: 'System.Windows.Forms.IconButton',
    xamlTag: 'Button',
    description: 'Интерактивная кнопка со встроенной графической иконкой',
  },
  SplitButton: {
    type: 'SplitButton',
    category: 'Common',
    displayName: 'SplitButton',
    icon: '🔘',
    defaultSize: { width: 140, height: 35 },
    defaultProps: { text: 'Действие ▼', enabled: true, visible: true },
    isContainer: false,
    csharpType: 'System.Windows.Forms.SplitButton',
    xamlTag: 'Button',
    description: 'Сегментированная кнопка с выпадающим меню дополнительных опций',
  },
  RepeatButton: {
    type: 'RepeatButton',
    category: 'Common',
    displayName: 'RepeatButton (Автоповтор)',
    icon: '🔘',
    defaultSize: { width: 120, height: 35 },
    defaultProps: { text: 'Удерживать', enabled: true, visible: true },
    isContainer: false,
    csharpType: 'System.Windows.Forms.RepeatButton',
    xamlTag: 'RepeatButton',
    description: 'Кнопка, которая генерирует событие Click непрерывно, пока она нажата',
  },

  // 2. Текст и числа
  TextBox: {
    type: 'TextBox',
    category: 'Common',
    displayName: 'Поле ввода (TextBox)',
    icon: '📝',
    defaultSize: { width: 180, height: 26 },
    defaultProps: { text: '', placeholder: 'Введите текст...', enabled: true, visible: true },
    isContainer: false,
    csharpType: 'System.Windows.Forms.TextBox',
    xamlTag: 'TextBox',
    description: 'Однострочное или многострочное поле для ввода текста пользователем',
  },
  PasswordBox: {
    type: 'PasswordBox',
    category: 'Common',
    displayName: 'Поле пароля (PasswordBox)',
    icon: '🔒',
    defaultSize: { width: 180, height: 26 },
    defaultProps: { text: '', placeholder: 'Пароль...', useSystemPasswordChar: true, enabled: true, visible: true },
    isContainer: false,
    csharpType: 'System.Windows.Forms.TextBox',
    xamlTag: 'TextBox',
    description: 'Поле ввода текста со скрытием символов звездочками для безопасности',
  },
  Label: {
    type: 'Label',
    category: 'Common',
    displayName: 'Метка (Label)',
    icon: '🏷️',
    defaultSize: { width: 100, height: 20 },
    defaultProps: { text: 'Текстовая метка', autoSize: true, enabled: true, visible: true },
    isContainer: false,
    csharpType: 'System.Windows.Forms.Label',
    xamlTag: 'TextBlock',
    description: 'Текстовая информационная надпись для заголовков и подсказок',
  },
  RichTextBox: {
    type: 'RichTextBox',
    category: 'Advanced',
    displayName: 'Текст RTF (RichTextBox)',
    icon: '📝',
    defaultSize: { width: 240, height: 120 },
    defaultProps: { text: 'Форматированный текст...', enabled: true, visible: true },
    isContainer: false,
    csharpType: 'System.Windows.Forms.RichTextBox',
    xamlTag: 'RichTextBox',
    description: 'Многострочное поле с поддержкой RTF разметки, цветного текста и расширенных шрифтов',
  },
  NumericUpDown: {
    type: 'NumericUpDown',
    category: 'Common',
    displayName: 'Счетчик (NumericUpDown)',
    icon: '🔢',
    defaultSize: { width: 120, height: 26 },
    defaultProps: { value: 0, minimum: 0, maximum: 100, enabled: true, visible: true },
    isContainer: false,
    csharpType: 'System.Windows.Forms.NumericUpDown',
    xamlTag: 'NumericUpDown',
    description: 'Числовое поле с кнопками инкремента и декремента со строгим диапазоном',
  },
  TrackBar: {
    type: 'TrackBar',
    category: 'Common',
    displayName: 'Слайдер (TrackBar)',
    icon: '🎚️',
    defaultSize: { width: 180, height: 35 },
    defaultProps: { value: 50, minimum: 0, maximum: 100, enabled: true, visible: true },
    isContainer: false,
    csharpType: 'System.Windows.Forms.TrackBar',
    xamlTag: 'Slider',
    description: 'Ползунковый регулятор для визуальной настройки числовых значений',
  },

  // 3. Списки и деревья
  ComboBox: {
    type: 'ComboBox',
    category: 'Common',
    displayName: 'Выпадающий список (ComboBox)',
    icon: '📋',
    defaultSize: { width: 180, height: 28 },
    defaultProps: { text: 'Выберите...', items: ['Элемент 1', 'Элемент 2'], enabled: true, visible: true },
    isContainer: false,
    csharpType: 'System.Windows.Forms.ComboBox',
    xamlTag: 'ComboBox',
    description: 'Выпадающий список с возможностью выбора значения из набора элементов',
  },
  ListBox: {
    type: 'ListBox',
    category: 'Common',
    displayName: 'Список (ListBox)',
    icon: '📜',
    defaultSize: { width: 160, height: 100 },
    defaultProps: { items: ['Строка 1', 'Строка 2', 'Строка 3'], enabled: true, visible: true },
    isContainer: false,
    csharpType: 'System.Windows.Forms.ListBox',
    xamlTag: 'ListBox',
    description: 'Прокручиваемый список записей для одиночного или множественного выбора',
  },
  CheckedListBox: {
    type: 'CheckedListBox',
    category: 'Common',
    displayName: 'Список с галочками',
    icon: '☑️',
    defaultSize: { width: 160, height: 100 },
    defaultProps: { items: ['Опция А', 'Опция Б', 'Опция В'], enabled: true, visible: true },
    isContainer: false,
    csharpType: 'System.Windows.Forms.CheckedListBox',
    xamlTag: 'ListBox',
    description: 'Список элементов, у каждого из которых имеется флажок выбора',
  },
  TreeView: {
    type: 'TreeView',
    category: 'Advanced',
    displayName: 'Дерево (TreeView)',
    icon: '🌲',
    defaultSize: { width: 200, height: 150 },
    defaultProps: { treeNodes: [{ id: '1', text: 'Корень' }, { id: '2', text: '├─ Узел 1' }], enabled: true, visible: true },
    isContainer: false,
    csharpType: 'System.Windows.Forms.TreeView',
    xamlTag: 'TreeView',
    description: 'Иерархическое дерево узлов с поддержкой раскрытия/схлопывания веток',
  },
  ListView: {
    type: 'ListView',
    category: 'Advanced',
    displayName: 'Список элементов (ListView)',
    icon: '📑',
    defaultSize: { width: 250, height: 140 },
    defaultProps: { view: 'Details', enabled: true, visible: true },
    isContainer: false,
    csharpType: 'System.Windows.Forms.ListView',
    xamlTag: 'ListView',
    description: 'Детализированный список элементов с настраиваемыми колонками',
  },
  DateTimePicker: {
    type: 'DateTimePicker',
    category: 'Common',
    displayName: 'Выбор даты (DateTimePicker)',
    icon: '📅',
    defaultSize: { width: 200, height: 26 },
    defaultProps: { format: 'Short', enabled: true, visible: true },
    isContainer: false,
    csharpType: 'System.Windows.Forms.DateTimePicker',
    xamlTag: 'DatePicker',
    description: 'Календарный контрол выбора даты и времени с нативным выпадающим календарем',
  },

  // 4. Меню и навигация
  MenuStrip: {
    type: 'MenuStrip',
    category: 'Menus',
    displayName: 'MenuStrip (Верхнее меню)',
    icon: '📑',
    defaultSize: { width: 400, height: 25 },
    defaultProps: { items: ['Файл', 'Правка', 'Вид', 'Справка'], enabled: true, visible: true },
    isContainer: false,
    csharpType: 'System.Windows.Forms.MenuStrip',
    xamlTag: 'Menu',
    description: 'Интерактивное главное меню окна с иерархическими выпадающими списками',
  },
  ToolStrip: {
    type: 'ToolStrip',
    category: 'Menus',
    displayName: 'ToolStrip (Иконки)',
    icon: '🛠️',
    defaultSize: { width: 300, height: 30 },
    defaultProps: { items: ['New', 'Open', 'Save'], enabled: true, visible: true },
    isContainer: false,
    csharpType: 'System.Windows.Forms.ToolStrip',
    xamlTag: 'ToolBar',
    description: 'Панель быстрого доступа с графическими кнопками команд',
  },
  StatusStrip: {
    type: 'StatusStrip',
    category: 'Menus',
    displayName: 'StatusStrip (Статус-бар)',
    icon: '📟',
    defaultSize: { width: 400, height: 22 },
    defaultProps: { text: 'Готово', enabled: true, visible: true },
    isContainer: false,
    csharpType: 'System.Windows.Forms.StatusStrip',
    xamlTag: 'StatusBar',
    description: 'Нижняя информационная панель статуса программы',
  },
  ContextMenuStrip: {
    type: 'ContextMenuStrip',
    category: 'Menus',
    displayName: 'ContextMenu (Меню по ПКМ)',
    icon: '🖱️',
    defaultSize: { width: 150, height: 80 },
    defaultProps: { items: ['Копировать', 'Вставить', 'Удалить'], enabled: true, visible: true },
    isContainer: false,
    csharpType: 'System.Windows.Forms.ContextMenuStrip',
    xamlTag: 'ContextMenu',
    description: 'Всплывающее контекстное меню, открывающееся при нажатии правой кнопкой мыши',
  },

  // 5. Контейнеры
  Panel: {
    type: 'Panel',
    category: 'Containers',
    displayName: 'Panel (Панель)',
    icon: '📦',
    defaultSize: { width: 250, height: 180 },
    defaultProps: { borderStyle: 'FixedSingle', backColor: '#1E1E24', enabled: true, visible: true },
    isContainer: true,
    csharpType: 'System.Windows.Forms.Panel',
    xamlTag: 'Canvas',
    description: 'Универсальный контейнер группировки дочерних элементов',
  },
  GroupBox: {
    type: 'GroupBox',
    category: 'Containers',
    displayName: 'GroupBox',
    icon: '🔲',
    defaultSize: { width: 260, height: 180 },
    defaultProps: { text: 'Параметры системы', enabled: true, visible: true },
    isContainer: true,
    csharpType: 'System.Windows.Forms.GroupBox',
    xamlTag: 'HeaderedContentControl',
    description: 'Рамочный контейнер с текстовым заголовком в верхней границе',
  },
  TabControl: {
    type: 'TabControl',
    category: 'Containers',
    displayName: 'TabControl (Вкладки)',
    icon: '📑',
    defaultSize: { width: 320, height: 200 },
    defaultProps: { tabPages: ['Вкладка 1', 'Вкладка 2'], enabled: true, visible: true },
    isContainer: true,
    csharpType: 'System.Windows.Forms.TabControl',
    xamlTag: 'TabControl',
    description: 'Многостраничный контейнер вкладок с независимыми дочерними поверхностями',
  },
  SplitContainer: {
    type: 'SplitContainer',
    category: 'Containers',
    displayName: 'SplitContainer',
    icon: '↔️',
    defaultSize: { width: 350, height: 220 },
    defaultProps: { orientation: 'Vertical', splitterDistance: 120, enabled: true, visible: true },
    isContainer: true,
    csharpType: 'System.Windows.Forms.SplitContainer',
    xamlTag: 'Grid',
    description: 'Разделенный контейнер, позволяющий изменять пропорции двух смежных областей',
  },

  // 6. Данные и графика
  DataGridView: {
    type: 'DataGridView',
    category: 'Data',
    displayName: 'DataGridView (Таблица)',
    icon: '▦',
    defaultSize: { width: 380, height: 200 },
    defaultProps: { columns: ['ID', 'Имя', 'Значение'], autoGenerateColumns: true, enabled: true, visible: true },
    isContainer: false,
    csharpType: 'System.Windows.Forms.DataGridView',
    xamlTag: 'DataGrid',
    description: 'Сетка для отображения и редактирования табличных массивов данных',
  },
  DataChart: {
    type: 'DataChart',
    category: 'Data',
    displayName: 'Chart (Графики/Диаграммы)',
    icon: '📈',
    defaultSize: { width: 320, height: 200 },
    defaultProps: { chartType: 'Line', title: 'График функции', enabled: true, visible: true },
    isContainer: false,
    csharpType: 'System.Windows.Forms.DataVisualization.Charting.Chart',
    xamlTag: 'Chart',
    description: 'Интерактивная диаграмма визуализации числовых массивов и графиков функций',
  },
  PictureBox: {
    type: 'PictureBox',
    category: 'Data',
    displayName: 'PictureBox',
    icon: '🖼️',
    defaultSize: { width: 140, height: 140 },
    defaultProps: { sizeMode: 'Zoom', borderStyle: 'FixedSingle', enabled: true, visible: true },
    isContainer: false,
    csharpType: 'System.Windows.Forms.PictureBox',
    xamlTag: 'Image',
    description: 'Контейнер отображения растровых или векторных изображений',
  },
  ProgressBar: {
    type: 'ProgressBar',
    category: 'Data',
    displayName: 'ProgressBar',
    icon: '📊',
    defaultSize: { width: 200, height: 24 },
    defaultProps: { value: 65, minimum: 0, maximum: 100, enabled: true, visible: true },
    isContainer: false,
    csharpType: 'System.Windows.Forms.ProgressBar',
    xamlTag: 'ProgressBar',
    description: 'Индикатор прогресса выполнения фоновых операций в процентах',
  },
  ColorPicker: {
    type: 'ColorPicker',
    category: 'Data',
    displayName: 'ColorPicker (Выбор цвета)',
    icon: '🎨',
    defaultSize: { width: 140, height: 35 },
    defaultProps: { color: '#2563EB', enabled: true, visible: true },
    isContainer: false,
    csharpType: 'System.Windows.Forms.ColorDialog',
    xamlTag: 'ColorPicker',
    description: 'Контрол выбора цвета из палитры',
  },

  // 7. Невизуальные компоненты
  Timer: {
    type: 'Timer',
    category: 'Advanced',
    displayName: 'Timer (Таймер)',
    icon: '⏱️',
    defaultSize: { width: 40, height: 40 },
    defaultProps: { interval: 1000, enabled: true, visible: false },
    isContainer: false,
    csharpType: 'System.Windows.Forms.Timer',
    xamlTag: 'Timer',
    description: 'Фоновый таймер, запускающий событие Tick с заданным интервалом',
  },
  BackgroundWorker: {
    type: 'BackgroundWorker',
    category: 'Advanced',
    displayName: 'BackgroundWorker',
    icon: '⚡️',
    defaultSize: { width: 40, height: 40 },
    defaultProps: { supportsCancellation: true, visible: false },
    isContainer: false,
    csharpType: 'System.ComponentModel.BackgroundWorker',
    xamlTag: 'BackgroundWorker',
    description: 'Компонент для выполнения длительных вычислений в фоновом потоке',
  },
  OpenFileDialog: {
    type: 'OpenFileDialog',
    category: 'Advanced',
    displayName: 'OpenFileDialog',
    icon: '📂',
    defaultSize: { width: 40, height: 40 },
    defaultProps: { filter: 'Все файлы (*.*)|*.*', visible: false },
    isContainer: false,
    csharpType: 'System.Windows.Forms.OpenFileDialog',
    xamlTag: 'OpenFileDialog',
    description: 'Диалоговое окно выбора файлов для открытия',
  },
  SaveFileDialog: {
    type: 'SaveFileDialog',
    category: 'Advanced',
    displayName: 'SaveFileDialog',
    icon: '💾',
    defaultSize: { width: 40, height: 40 },
    defaultProps: { filter: 'Текстовые (*.txt)|*.txt', visible: false },
    isContainer: false,
    csharpType: 'System.Windows.Forms.SaveFileDialog',
    xamlTag: 'SaveFileDialog',
    description: 'Диалоговое окно выбора пути сохранения файла',
  }
};

export const getAllRegistryControls = (): ControlMetadata[] => {
  return Object.values(COMPONENT_REGISTRY);
};

export const getRegistryControl = (type: ControlType): ControlMetadata | undefined => {
  return COMPONENT_REGISTRY[type];
};
