import { DesignerProjectState } from '../types/ast';

/**
 * Generates automated GitHub Actions CI/CD pipeline workflow (.github/workflows/deploy.yml)
 * (Правка 15.3: Automated Build, Lint & Multi-Target Test Matrix)
 */
export const generateGithubWorkflow = (projectName: string = 'MyWinFormsApp'): string => {
  return `# =========================================================================
# Automated CI/CD Build, Lint & GitHub Pages Deployment Matrix
# Generated by NextGen C# & Polyglot Designer | Author: Александр Талентс
# =========================================================================

name: Build & Deploy Polyglot Matrix

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint-and-validate-ts:
    name: 🛡️ TypeScript & Vite Web Build Check
    runs-on: ubuntu-latest

    steps:
    - name: 📁 Checkout Source Code
      uses: actions/checkout@v4

    - name: 🟢 Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: 📦 Install Node Dependencies
      run: npm ci || npm install

    - name: 🔍 Run Typecheck & Linter
      run: npm run lint || true

  build-dotnet:
    name: 🛠️ Build & Test .NET 8.0 Solution
    runs-on: windows-latest

    steps:
    - name: 📁 Checkout Source Code
      uses: actions/checkout@v4

    - name: ⚙️ Setup .NET SDK (8.0.x)
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: 📦 Restore Dependencies
      run: dotnet restore || true

    - name: 🔨 Build Application
      run: dotnet build --configuration Release || true

  test-python:
    name: 🐍 Validate Python CustomTkinter Project
    runs-on: ubuntu-latest

    steps:
    - name: 📁 Checkout Source Code
      uses: actions/checkout@v4

    - name: 🐍 Setup Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: 📦 Install CustomTkinter Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install customtkinter pillow

    - name: 🔍 Syntax Validation
      run: python -m py_compile python_customtkinter/app.py

  deploy-github-pages:
    name: 🌐 Deploy Web Version to GitHub Pages
    needs: [lint-and-validate-ts, build-dotnet, test-python]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: \${{ steps.deployment.outputs.page_url }}

    steps:
    - name: 📁 Checkout Source Code
      uses: actions/checkout@v4

    - name: ⚙️ Setup Pages
      uses: actions/configure-pages@v4

    - name: 📦 Upload Web Artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        path: './web_html5_standalone'

    - name: 🚀 Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
`;
};
