import { DesignerProjectState, DesignerNode } from '../types/ast';

export interface ResxResourceEntry {
  id: string;
  key: string;
  comment?: string;
  type: 'string' | 'image' | 'icon' | 'binary';
  values: Record<string, string>; // culture code -> value, e.g. { 'default': 'Hello', 'ru-RU': 'Привет', 'de-DE': 'Hallo' }
}

export interface SupportedLocale {
  code: string;
  name: string;
  flag: string;
}

export const SUPPORTED_LOCALES: SupportedLocale[] = [
  { code: 'default', name: 'Default (en-US)', flag: '🇺🇸' },
  { code: 'ru-RU', name: 'Русский (ru-RU)', flag: '🇷🇺' },
  { code: 'de-DE', name: 'Deutsch (de-DE)', flag: '🇩🇪' },
  { code: 'es-ES', name: 'Español (es-ES)', flag: '🇪🇸' },
  { code: 'fr-FR', name: 'Français (fr-FR)', flag: '🇫🇷' },
  { code: 'zh-CN', name: '中文 (zh-CN)', flag: '🇨🇳' },
  { code: 'ja-JP', name: '日本語 (ja-JP)', flag: '🇯🇵' },
];

export class ResxLocalizationEngine {
  /**
   * Initializes initial resource set extracted from existing form components
   */
  public static extractFromProject(project: DesignerProjectState): ResxResourceEntry[] {
    const entries: ResxResourceEntry[] = [
      {
        id: 'res-app-title',
        key: 'App_Title',
        comment: 'Главный заголовок приложения',
        type: 'string',
        values: {
          default: project.projectName || 'My Application',
          'ru-RU': project.projectName || 'Мое Приложение',
          'de-DE': project.projectName || 'Meine Anwendung',
          'es-ES': project.projectName || 'Mi Aplicación',
        },
      },
      {
        id: 'res-btn-submit',
        key: 'btnSubmit_Text',
        comment: 'Кнопка отправки / расчета',
        type: 'string',
        values: {
          default: 'Calculate',
          'ru-RU': 'Рассчитать',
          'de-DE': 'Berechnen',
          'es-ES': 'Calcular',
        },
      },
      {
        id: 'res-btn-cancel',
        key: 'btnCancel_Text',
        comment: 'Кнопка отмены',
        type: 'string',
        values: {
          default: 'Cancel',
          'ru-RU': 'Отмена',
          'de-DE': 'Abbrechen',
          'es-ES': 'Cancelar',
        },
      },
      {
        id: 'res-msg-success',
        key: 'Msg_OperationSuccessful',
        comment: 'Уведомление об успешной операции',
        type: 'string',
        values: {
          default: 'Operation completed successfully!',
          'ru-RU': 'Операция успешно завершена!',
          'de-DE': 'Vorgang erfolgreich abgeschlossen!',
          'es-ES': '¡Operación completada con éxito!',
        },
      },
      {
        id: 'res-msg-error',
        key: 'Msg_OperationFailed',
        comment: 'Сообщение об ошибке',
        type: 'string',
        values: {
          default: 'An error occurred during calculation.',
          'ru-RU': 'Произошла ошибка при выполнении расчета.',
          'de-DE': 'Beim Berechnen ist ein Fehler aufgetreten.',
          'es-ES': 'Se produjo un error durante el cálculo.',
        },
      },
    ];

    // Extract text from form nodes
    Object.values(project.nodes).forEach((node) => {
      if (node.properties?.text && node.properties?.name && node.type !== 'Form') {
        const key = `${node.properties.name}_Text`;
        const exists = entries.some((e) => e.key === key);
        if (!exists) {
          entries.push({
            id: `res-ctrl-${node.id}`,
            key,
            comment: `Текст элемента ${node.properties.name} (${node.type})`,
            type: 'string',
            values: {
              default: node.properties.text,
              'ru-RU': node.properties.text,
              'de-DE': node.properties.text,
              'es-ES': node.properties.text,
            },
          });
        }
      }
    });

    return entries;
  }

  /**
   * Generates strongly-typed C# Resources.Designer.cs
   */
  public static generateDesignerCs(namespaceName: string, entries: ResxResourceEntry[]): string {
    const propsCode = entries
      .map((entry) => {
        const doc = entry.comment ? `\n        /// <summary>\n        ///   ${entry.comment}\n        /// </summary>` : '';
        return `${doc}
        public static string ${entry.key}
        {
            get
            {
                return ResourceManager.GetString("${entry.key}", resourceCulture);
            }
        }`;
      })
      .join('\n');

    return `//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментом Roslyn .resx Studio.
//     Версия среды выполнения: 4.0.30319.42000
// </auto-generated>
//------------------------------------------------------------------------------

namespace ${namespaceName || 'MyApplication'}.Properties
{
    using System;

    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() { }

        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, используемый этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("${namespaceName || 'MyApplication'}.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Переопределяет свойство CurrentUICulture текущего потока для всех обращений к ресурсам.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }
${propsCode}
    }
}
`;
  }

  /**
   * Generates standard XML .resx format string
   */
  public static generateResxXml(entries: ResxResourceEntry[], culture: string = 'default'): string {
    const dataNodes = entries
      .map((entry) => {
        const val = entry.values[culture] || entry.values['default'] || '';
        const comment = entry.comment ? `\n    <comment>${escapeXml(entry.comment)}</comment>` : '';
        return `  <data name="${escapeXml(entry.key)}" xml:space="preserve">
    <value>${escapeXml(val)}</value>${comment}
  </data>`;
      })
      .join('\n');

    return `<?xml version="1.0" encoding="utf-8"?>
<root>
  <resheader name="resmimetype">
    <value>text/microsoft-resx</value>
  </resheader>
  <resheader name="version">
    <value>2.0</value>
  </resheader>
  <resheader name="reader">
    <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <resheader name="writer">
    <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
${dataNodes}
</root>`;
  }

  /**
   * Applies localized strings to canvas nodes for the chosen culture
   */
  public static applyLocalizationToNodes(
    nodes: Record<string, DesignerNode>,
    entries: ResxResourceEntry[],
    culture: string
  ): Record<string, DesignerNode> {
    const updated = { ...nodes };

    Object.entries(updated).forEach(([id, node]) => {
      const key = `${node.properties?.name}_Text`;
      const entry = entries.find((e) => e.key === key);
      if (entry) {
        const val = entry.values[culture] || entry.values['default'];
        if (val !== undefined) {
          updated[id] = {
            ...node,
            properties: {
              ...node.properties,
              text: val,
            },
          };
        }
      }
    });

    return updated;
  }
}

function escapeXml(unsafe: string): string {
  return unsafe
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}
