import { DesignerProjectState, DesignerNode, ControlType, NodeProperties } from '../types/ast';

export interface TemplateDefinition {
  id: string;
  num: number;
  category: 'business' | 'education' | 'tools' | 'media' | 'network' | 'text' | 'games' | 'security' | 'automation' | 'iot';
  categoryTitle: string;
  title: string;
  icon: string;
  description: string;
  controlsCount: number;
  hasDatabase: boolean;
  dbTableName?: string;
  controlsList: string[];
  csharpSummary: string;
  tags: string[];
}

export const TEMPLATES_CATALOG: TemplateDefinition[] = [
  // 💼 КАТЕГОРИЯ 1: БИЗНЕС, СКЛАД И CRM (01–10)
  {
    id: 'tpl_01',
    num: 1,
    category: 'business',
    categoryTitle: '💼 Бизнес и Склад',
    title: 'Учет склада и остатков',
    icon: '📦',
    description: 'Таблица товаров, поиск по артикулу, добавление позиций, учет остатка и стоимости.',
    controlsCount: 8,
    hasDatabase: true,
    dbTableName: 'Products',
    controlsList: ['DataGridView', 'TextBox (Поиск)', 'Button (Добавить)', 'NumericUpDown (Остаток)', 'Button (Удалить)'],
    csharpSummary: 'SQLite таблица Products, авто-расчет общей стоимости склада, фильтрация по категориям.',
    tags: ['склад', 'товары', 'sqlite', 'таблица', 'бизнес'],
  },
  {
    id: 'tpl_02',
    num: 2,
    category: 'business',
    categoryTitle: '💼 Бизнес и Склад',
    title: 'CRM клиентов и заказов',
    icon: '👥',
    description: 'Вкладки клиентов и заказов, воронка продаж, статусы оплаты и экспорт отчетов.',
    controlsCount: 12,
    hasDatabase: true,
    dbTableName: 'Clients & Orders',
    controlsList: ['TabControl', 'DataGridView', 'ComboBox (Статус)', 'TextBox (Поиск)', 'Button (Экспорт)'],
    csharpSummary: 'Выборка заказов по статусам (В обработке/Оплачен), фильтрация клиентов, экспорт в CSV.',
    tags: ['crm', 'клиенты', 'заказы', 'продажи', 'бизнес'],
  },
  {
    id: 'tpl_03',
    num: 3,
    category: 'business',
    categoryTitle: '💼 Бизнес и Склад',
    title: 'Генератор счетов-фактур',
    icon: '🧾',
    description: 'Поля реквизитов поставщика и покупателя, таблица услуг, авто-расчет НДС 20% и итога.',
    controlsCount: 10,
    hasDatabase: false,
    controlsList: ['TextBox (ИНН/КПП)', 'DataGridView (Услуги)', 'NumericUpDown (Кол-во)', 'Button (Печать)'],
    csharpSummary: 'Расчет НДС 20%, формирование квитанции, экспорт печатной формы в HTML/PDF.',
    tags: ['счет', 'фактура', 'ндс', 'документы', 'бухгалтерия'],
  },
  {
    id: 'tpl_04',
    num: 4,
    category: 'business',
    categoryTitle: '💼 Бизнес и Склад',
    title: 'Табель учета сотрудников',
    icon: '👔',
    description: 'Таблица персонала, выбор отдела, учет рабочих смен, больничных и отпусков.',
    controlsCount: 9,
    hasDatabase: true,
    dbTableName: 'Employees',
    controlsList: ['DataGridView', 'ComboBox (Отдел)', 'DateTimePicker', 'Button (Табель)'],
    csharpSummary: 'Подсчет отработанных часов за месяц, учет рабочих дней и фильтр по должностям.',
    tags: ['кадры', 'сотрудники', 'табель', 'зарплата', 'hrm'],
  },
  {
    id: 'tpl_05',
    num: 5,
    category: 'business',
    categoryTitle: '💼 Бизнес и Склад',
    title: 'Бюджет доходов и расходов',
    icon: '💰',
    description: 'Круговая диаграмма распределения трат, категории расходов, баланс и лимиты.',
    controlsCount: 8,
    hasDatabase: true,
    dbTableName: 'Transactions',
    controlsList: ['DataChart (Диаграмма)', 'DataGridView', 'NumericUpDown (Сумма)', 'ComboBox (Категория)'],
    csharpSummary: 'Авто-подсчет остатка бюджета, круговая аналитика по статьям расходов, алерт о перерасходе.',
    tags: ['бюджет', 'финансы', 'деньги', 'график', 'доходы'],
  },
  {
    id: 'tpl_06',
    num: 6,
    category: 'business',
    categoryTitle: '💼 Бизнес и Склад',
    title: 'Автопарк и путевые листы',
    icon: '🚚',
    description: 'Список автомобилей, пробег, остаток топлива, маршруты и водители.',
    controlsCount: 9,
    hasDatabase: true,
    dbTableName: 'Vehicles',
    controlsList: ['DataGridView (Авто)', 'TextBox (Маршрут)', 'NumericUpDown (Пробег)', 'Button (Лист)'],
    csharpSummary: 'Расчет среднего расхода бензина на 100 км по формуле, учет ТО и путевых листов.',
    tags: ['автопарк', 'логистика', 'машины', 'топливо', 'водители'],
  },
  {
    id: 'tpl_07',
    num: 7,
    category: 'business',
    categoryTitle: '💼 Бизнес и Склад',
    title: 'Регистратура медклиники',
    icon: '🏥',
    description: 'Электронная медицинская карта, выбор специалиста, расписание приемов.',
    controlsCount: 10,
    hasDatabase: true,
    dbTableName: 'Appointments',
    controlsList: ['ListBox (Врачи)', 'DateTimePicker', 'TextBox (Пациент)', 'Button (Запись)'],
    csharpSummary: 'Запись пациента на свободный слот времени с валидацией пересечения расписаний.',
    tags: ['медицина', 'клиника', 'врачи', 'пациенты', 'запись'],
  },
  {
    id: 'tpl_08',
    num: 8,
    category: 'business',
    categoryTitle: '💼 Бизнес и Склад',
    title: 'Электронная библиотека',
    icon: '📖',
    description: 'Каталог книг, обложки, авторы, жанры, статус (Выдана/В фонде) и сроки возврата.',
    controlsCount: 8,
    hasDatabase: true,
    dbTableName: 'Books',
    controlsList: ['DataGridView', 'PictureBox (Обложка)', 'TextBox (Поиск)', 'Button (Выдать)'],
    csharpSummary: 'Поиск по автору, названию и ISBN, учет даты выдачи и автоматический расчет просрочки.',
    tags: ['книги', 'библиотека', 'каталог', 'учет', 'литература'],
  },
  {
    id: 'tpl_09',
    num: 9,
    category: 'business',
    categoryTitle: '💼 Бизнес и Склад',
    title: 'Бронирование номеров отеля',
    icon: '🏨',
    description: 'Визуальная сетка комнат (Люкс, Стандарт), выбор дат заезда и выезда, расчет суммы.',
    controlsCount: 11,
    hasDatabase: true,
    dbTableName: 'Rooms',
    controlsList: ['DataGridView (Шахматка)', 'DateTimePicker (Заезд)', 'DateTimePicker (Выезд)', 'Button'],
    csharpSummary: 'Расчет стоимости проживания с учетом количества суток и категории номера.',
    tags: ['отель', 'гостиница', 'бронь', 'номера', 'туризм'],
  },
  {
    id: 'tpl_10',
    num: 10,
    category: 'business',
    categoryTitle: '💼 Бизнес и Склад',
    title: 'Кассовый POS-терминал',
    icon: '🛒',
    description: 'Кнопки быстрого выбора популярных товаров, чек, подсчет сдачи и печать фискального чека.',
    controlsCount: 14,
    hasDatabase: true,
    dbTableName: 'PosProducts',
    controlsList: ['ListBox (Чек)', 'TextBox (Внесено)', 'Label (Сдача)', '8x Button (Товары)'],
    csharpSummary: 'Накопление чека, расчет скидки, расчет сдачи от внесенных купюр и очистка заказа.',
    tags: ['касса', 'pos', 'магазин', 'чек', 'деньги'],
  },

  // 🎓 КАТЕГОРИЯ 2: УНИВЕРСИТЕТ, НАУКА И ЛАБОРАТОРНЫЕ (11–20)
  {
    id: 'tpl_11',
    num: 11,
    category: 'education',
    categoryTitle: '🎓 Университет и Лабы',
    title: 'Матричный калькулятор 4×4',
    icon: '🔢',
    description: 'Ввод матриц A и B, определитель Det, умножение, транспонирование, метод Гаусса.',
    controlsCount: 22,
    hasDatabase: false,
    controlsList: ['16x TextBox (Матрица A)', '16x TextBox (Матрица B)', 'Button (Det)', 'Button (A×B)'],
    csharpSummary: 'Расчет определителя методом Гаусса, умножение матриц, нахождение обратной матрицы.',
    tags: ['матрицы', 'алгебра', 'вышмат', 'гаусс', 'лабораторная'],
  },
  {
    id: 'tpl_12',
    num: 12,
    category: 'education',
    categoryTitle: '🎓 Университет и Лабы',
    title: 'Численное интегрирование',
    icon: '📈',
    description: 'Интегрирование методом трапеций и Симпсона, график подынтегральной функции.',
    controlsCount: 8,
    hasDatabase: false,
    controlsList: ['DataChart (График)', 'TextBox (a, b, n)', 'ComboBox (Функция)', 'Button (Расчет)'],
    csharpSummary: 'Вычисление определенного интеграла методами прямоугольников, трапеций и парабол (Симпсона).',
    tags: ['интеграл', 'численные методы', 'симпсон', 'график', 'математика'],
  },
  {
    id: 'tpl_13',
    num: 13,
    category: 'education',
    categoryTitle: '🎓 Университет и Лабы',
    title: 'Физический маятник',
    icon: '⚖️',
    description: 'Симуляция колебаний маятника с затуханием, ползунки длины нити, массы и угла.',
    controlsCount: 7,
    hasDatabase: false,
    controlsList: ['PictureBox (Анимация)', 'TrackBar (Длина)', 'TrackBar (Масса)', 'Timer (60 FPS)'],
    csharpSummary: 'Численное интегрирование дифура колебаний методом Рунге-Кутты с плавной 2D-отрисовкой.',
    tags: ['физика', 'маятник', 'симуляция', 'колебания', 'механика'],
  },
  {
    id: 'tpl_14',
    num: 14,
    category: 'education',
    categoryTitle: '🎓 Университет и Лабы',
    title: 'Журнал успеваемости (GPA)',
    icon: '📚',
    description: 'Таблица дисциплин, оценки по 100-балльной шкале, средний балл GPA и подсветка долгов.',
    controlsCount: 7,
    hasDatabase: true,
    dbTableName: 'Grades',
    controlsList: ['DataGridView', 'TextBox (Предмет)', 'NumericUpDown (Оценка)', 'Label (GPA)'],
    csharpSummary: 'Вычисление взвешенного рейтинга GPA, статистика успеваемости группы, экспорт ведомости.',
    tags: ['деканат', 'оценки', 'gpa', 'студенты', 'учеба'],
  },
  {
    id: 'tpl_15',
    num: 15,
    category: 'education',
    categoryTitle: '🎓 Университет и Лабы',
    title: 'Генератор экзаменационных тестов',
    icon: '📝',
    description: 'Окно тестирования студентов, варианты ответов, таймер с обратным отсчетом и оценка.',
    controlsCount: 8,
    hasDatabase: true,
    dbTableName: 'Questions',
    controlsList: ['Label (Вопрос)', '4x RadioButton', 'ProgressBar (Таймер)', 'Button (Ответить)'],
    csharpSummary: 'Рандомизация вопросов, проверка правильности ответов, выставление оценки (2, 3, 4, 5).',
    tags: ['тесты', 'экзамен', 'квиз', 'опросы', 'студенты'],
  },
  {
    id: 'tpl_16',
    num: 16,
    category: 'education',
    categoryTitle: '🎓 Университет и Лабы',
    title: 'Графы и алгоритм Дейкстры',
    icon: '🕸️',
    description: 'Холст интерактивного добавления вершин и ребер графа, поиск кратчайшего пути.',
    controlsCount: 6,
    hasDatabase: false,
    controlsList: ['PictureBox (Холст)', 'TextBox (Старт/Финиш)', 'Button (Дейкстра)', 'Label (Длина)'],
    csharpSummary: 'Алгоритм Дейкстры нахождения кратчайшего маршрута в графе с визуальной подсветкой пути.',
    tags: ['графы', 'дейкстра', 'алгоритмы', 'дискретная математика', 'пути'],
  },
  {
    id: 'tpl_17',
    num: 17,
    category: 'education',
    categoryTitle: '🎓 Университет и Лабы',
    title: 'Таблица Менделеева',
    icon: '🧪',
    description: 'Интерактивная химическая таблица, атомные массы, валентность, расчет молярной массы.',
    controlsCount: 12,
    hasDatabase: false,
    controlsList: ['DataGridView (Элементы)', 'TextBox (Формула: H2SO4)', 'Button (Расчет массы)'],
    csharpSummary: 'Парсинг химических формул, суммирование атомных весов элементов, справочник изотопов.',
    tags: ['химия', 'менделеев', 'молекулы', 'элементы', 'наука'],
  },
  {
    id: 'tpl_18',
    num: 18,
    category: 'education',
    categoryTitle: '🎓 Университет и Лабы',
    title: 'Статистика и регрессия',
    icon: '📊',
    description: 'Ввод выборки чисел, расчет среднего, дисперсии, медианы и построение линии тренда.',
    controlsCount: 7,
    hasDatabase: false,
    controlsList: ['TextBox (Числа)', 'DataChart (Точки и Тренд)', 'Label (Дисперсия)', 'Button'],
    csharpSummary: 'Линейная регрессия методом наименьших квадратов (МНК), расчет коэффициента Пирсона.',
    tags: ['статистика', 'мнк', 'регрессия', 'анализ', 'математика'],
  },
  {
    id: 'tpl_19',
    num: 19,
    category: 'education',
    categoryTitle: '🎓 Университет и Лабы',
    title: 'Конвертер систем счисления',
    icon: '🧮',
    description: 'Мгновенный двусторонний пересчет чисел между двоичной (BIN), 8-й, 10-й и 16-й (HEX).',
    controlsCount: 6,
    hasDatabase: false,
    controlsList: ['TextBox (DEC)', 'TextBox (HEX)', 'TextBox (BIN)', 'TextBox (OCT)'],
    csharpSummary: 'Конвертация систем счисления произвольной длины, битовые операции и побитовые маски.',
    tags: ['bin', 'hex', 'dec', 'биты', 'информатика'],
  },
  {
    id: 'tpl_20',
    num: 20,
    category: 'education',
    categoryTitle: '🎓 Университет и Лабы',
    title: 'Симулятор логических схем',
    icon: '⚡',
    description: 'Вентили AND, OR, NOT, XOR, входы A и B, построение таблицы истинности схемы.',
    controlsCount: 9,
    hasDatabase: false,
    controlsList: ['CheckBox (Вход A)', 'CheckBox (Вход B)', 'ComboBox (Вентиль)', 'Label (Выход Q)'],
    csharpSummary: 'Построение полной таблицы истинности для булевых функций и логических цепочек.',
    tags: ['логика', 'схемотехника', 'and', 'or', 'xor'],
  },

  // 🛠 КАТЕГОРИЯ 3: СИСТЕМНЫЕ УТИЛИТЫ И ДИАГНОСТИКА ПК (21–30)
  {
    id: 'tpl_21',
    num: 21,
    category: 'tools',
    categoryTitle: '🛠 Системные Утилиты',
    title: 'Диспетчер процессов ПК',
    icon: '⚙️',
    description: 'Список активных процессов Windows, загрузка ОЗУ и CPU, кнопка завершения процесса.',
    controlsCount: 7,
    hasDatabase: false,
    controlsList: ['DataGridView (Процессы)', 'TextBox (Поиск)', 'Button (Завершить)', 'Timer'],
    csharpSummary: 'Опрос Process.GetProcesses(), замер использования рабочей памяти и PID.',
    tags: ['диспетчер', 'процессы', 'память', 'windows', 'система'],
  },
  {
    id: 'tpl_22',
    num: 22,
    category: 'tools',
    categoryTitle: '🛠 Системные Утилиты',
    title: 'Пакетный ренеймер файлов',
    icon: '🏷️',
    description: 'Массовое переименование файлов по маске (photo_{index}, doc_{date}) с предпросмотром.',
    controlsCount: 8,
    hasDatabase: false,
    controlsList: ['ListBox (Файлы)', 'TextBox (Шаблон)', 'Button (Выбрать папку)', 'Button (Переименовать)'],
    csharpSummary: 'Пакетная обработка файловых дескрипторов с защитой от коллизий и дублирования имен.',
    tags: ['файлы', 'ренеймер', 'пакетно', 'папки', 'утилита'],
  },
  {
    id: 'tpl_23',
    num: 23,
    category: 'tools',
    categoryTitle: '🛠 Системные Утилиты',
    title: 'Очиститель временного мусора',
    icon: '🧹',
    description: 'Сканирование папок %TEMP%, кэшей браузеров, корзины и освобождение места на диске.',
    controlsCount: 7,
    hasDatabase: false,
    controlsList: ['ProgressBar', 'ListBox (Найденные файлы)', 'Label (Освобождено)', 'Button (Очистить)'],
    csharpSummary: 'Безопасная очистка системных каталогов временных файлов с пропуском заблокированных дескрипторов.',
    tags: ['очистка', 'temp', 'диск', 'мусор', 'оптимизация'],
  },
  {
    id: 'tpl_24',
    num: 24,
    category: 'tools',
    categoryTitle: '🛠 Системные Утилиты',
    title: 'Сетевой пинг-сканер IP',
    icon: '📡',
    description: 'Сканирование подсети (192.168.1.1–254), определение активных хостов и времени отклика.',
    controlsCount: 7,
    hasDatabase: false,
    controlsList: ['DataGridView', 'TextBox (Диапазон IP)', 'Button (Старт)', 'ProgressBar'],
    csharpSummary: 'Асинхронный многопоточный пинг хостов через System.Net.NetworkInformation.Ping.',
    tags: ['ping', 'сеть', 'ip', 'сканер', 'lan'],
  },
  {
    id: 'tpl_25',
    num: 25,
    category: 'tools',
    categoryTitle: '🛠 Системные Утилиты',
    title: 'Генератор надежных паролей',
    icon: '🔑',
    description: 'Ползунок длины (8–64), чекбоксы цифр, спецсимволов, оценка энтропии и кнопка копирования.',
    controlsCount: 8,
    hasDatabase: false,
    controlsList: ['TrackBar (Длина)', 'CheckBox (A-Z)', 'CheckBox (0-9)', 'CheckBox (!@#)', 'TextBox'],
    csharpSummary: 'Криптографическая генерация с использованием RandomNumberGenerator и расчет энтропии.',
    tags: ['пароли', 'безопасность', 'генератор', 'ключи', 'крипто'],
  },
  {
    id: 'tpl_26',
    num: 26,
    category: 'tools',
    categoryTitle: '🛠 Системные Утилиты',
    title: 'Хеш-калькулятор файлов',
    icon: '🛡️',
    description: 'Перетаскивание файла (Drag & Drop), мгновенный расчет контрольных сумм MD5, SHA-256.',
    controlsCount: 6,
    hasDatabase: false,
    controlsList: ['Panel (Drop Area)', 'TextBox (MD5)', 'TextBox (SHA-256)', 'Button (Сравнить)'],
    csharpSummary: 'Потоковое вычисление хешей файлов через System.Security.Cryptography.SHA256.',
    tags: ['хеш', 'md5', 'sha256', 'целостность', 'крипто'],
  },
  {
    id: 'tpl_27',
    num: 27,
    category: 'tools',
    categoryTitle: '🛠 Системные Утилиты',
    title: 'Монитор скорости сети',
    icon: '📶',
    description: 'Живой график сетевого трафика, замер входящей и исходящей скорости в КБ/с.',
    controlsCount: 6,
    hasDatabase: false,
    controlsList: ['DataChart (Трафик)', 'Label (Скорость КБ/с)', 'ComboBox (Сетевой адаптер)', 'Timer'],
    csharpSummary: 'Чтение счетчиков байтов сетевых адаптеров NetworkInterface.GetIPv4Statistics().',
    tags: ['сеть', 'скорость', 'интернет', 'трафик', 'монитор'],
  },
  {
    id: 'tpl_28',
    num: 28,
    category: 'tools',
    categoryTitle: '🛠 Системные Утилиты',
    title: 'Менеджер автозапуска Windows',
    icon: '🚀',
    description: 'Список программ из реестра HKCU\\Run и HKLM\\Run, включение и отключение автозагрузки.',
    controlsCount: 6,
    hasDatabase: false,
    controlsList: ['DataGridView', 'Button (Добавить)', 'Button (Удалить)', 'Button (Обновить)'],
    csharpSummary: 'Чтение и запись ключей в ветках реестра Microsoft\\Windows\\CurrentVersion\\Run.',
    tags: ['автозапуск', 'реестр', 'windows', 'старт', 'утилита'],
  },
  {
    id: 'tpl_29',
    num: 29,
    category: 'tools',
    categoryTitle: '🛠 Системные Утилиты',
    title: 'Поиск дубликатов файлов',
    icon: '🔍',
    description: 'Сканирование выбранного каталога, группировка одинаковых файлов по хешу и размеру.',
    controlsCount: 7,
    hasDatabase: false,
    controlsList: ['ListBox (Дубликаты)', 'Button (Выбрать папку)', 'ProgressBar', 'Button (Удалить)'],
    csharpSummary: 'Двухэтапная проверка: быстрая фильтрация по размеру + точный SHA-256 хеш.',
    tags: ['дубликаты', 'файлы', 'диск', 'очистка', 'поиск'],
  },
  {
    id: 'tpl_30',
    num: 30,
    category: 'tools',
    categoryTitle: '🛠 Системные Утилиты',
    title: 'Редактор конфигураций INI/JSON',
    icon: '⚙️',
    description: 'Иерархическое дерево настроек, удобное изменение параметров без ошибок синтаксиса.',
    controlsCount: 7,
    hasDatabase: false,
    controlsList: ['TreeView (Секции)', 'DataGridView (Ключ-Значение)', 'Button (Сохранить)'],
    csharpSummary: 'Парсинг файлов INI и JSON в единую объектную модель настроек программы.',
    tags: ['ini', 'json', 'конфиг', 'настройки', 'структура'],
  },

  // 🎬 КАТЕГОРИЯ 4: МУЛЬТИМЕДИА, АУДИО И ГРАФИКА (31–40)
  {
    id: 'tpl_31',
    num: 31,
    category: 'media',
    categoryTitle: '🎬 Мультимедиа и Графика',
    title: 'MP3/WAV Аудиоплеер',
    icon: '🎵',
    description: 'Список треков, шкала перемотки TrackBar, регулятор громкости, время трека.',
    controlsCount: 8,
    hasDatabase: false,
    controlsList: ['ListBox (Плейлист)', 'TrackBar (Прогресс)', 'TrackBar (Громкость)', 'Button (Play/Pause)'],
    csharpSummary: 'Воспроизведение звуковых дорожек, обработка паузы, перемотки и смена треков.',
    tags: ['музыка', 'плеер', 'mp3', 'звук', 'аудио'],
  },
  {
    id: 'tpl_32',
    num: 32,
    category: 'media',
    categoryTitle: '🎬 Мультимедиа и Графика',
    title: 'Видеоплеер с плейлистом',
    icon: '🎥',
    description: 'Экран видео, управление воспроизведением, поддержка полноэкранного режима.',
    controlsCount: 7,
    hasDatabase: false,
    controlsList: ['Panel (Видео холст)', 'Button (Play)', 'TrackBar (Таймлайн)', 'ListBox (Ролики)'],
    csharpSummary: 'Управление потоковым медиаплеером, масштабирование видеокадра под размер окна.',
    tags: ['видео', 'плеер', 'кино', 'ролики', 'медиа'],
  },
  {
    id: 'tpl_33',
    num: 33,
    category: 'media',
    categoryTitle: '🎬 Мультимедиа и Графика',
    title: 'Фотогалерея со слайдшоу',
    icon: '🖼️',
    description: 'Миниатюры картинок, зум колесиком мыши, автоматическое слайдшоу по таймеру.',
    controlsCount: 7,
    hasDatabase: false,
    controlsList: ['PictureBox (Фото)', 'ListBox (Миниатюры)', 'Button (Слайдшоу)', 'Timer'],
    csharpSummary: 'Плавная смена кадров, предпросмотр каталога изображений с масштабированием.',
    tags: ['фото', 'галерея', 'слайдшоу', 'картинки', 'просмотр'],
  },
  {
    id: 'tpl_34',
    num: 34,
    category: 'media',
    categoryTitle: '🎬 Мультимедиа и Графика',
    title: 'Мини-Paint (Рисовалка)',
    icon: '🎨',
    description: 'Выбор цвета кисти, толщина линии, ластик, заливка и сохранение рисунка в PNG.',
    controlsCount: 9,
    hasDatabase: false,
    controlsList: ['PictureBox (Холст)', 'TrackBar (Толщина)', 'Button (Цвет)', 'Button (Сохранить)'],
    csharpSummary: 'Рисование пером по объекту Bitmap через Graphics.DrawLine с обработкой сглаживания.',
    tags: ['paint', 'рисование', 'холст', 'графика', 'png'],
  },
  {
    id: 'tpl_35',
    num: 35,
    category: 'media',
    categoryTitle: '🎬 Мультимедиа и Графика',
    title: 'Редактор ID3 тегов аудио',
    icon: '🏷️',
    description: 'Просмотр и редактирование метаданных MP3: Артист, Альбом, Год, Трек, Обложка.',
    controlsCount: 8,
    hasDatabase: false,
    controlsList: ['TextBox (Артист)', 'TextBox (Альбом)', 'NumericUpDown (Год)', 'Button (Сохранить)'],
    csharpSummary: 'Чтение и перезапись ID3v2 тегов в бинарном заголовке музыкальных файлов.',
    tags: ['id3', 'mp3', 'теги', 'музыка', 'метаданные'],
  },
  {
    id: 'tpl_36',
    num: 36,
    category: 'media',
    categoryTitle: '🎬 Мультимедиа и Графика',
    title: 'Конвертер картинок в ICO',
    icon: '💠',
    description: 'Загрузка PNG/JPG, генератор многослойных Windows .ICO иконок (16, 32, 48, 256px).',
    controlsCount: 7,
    hasDatabase: false,
    controlsList: ['PictureBox (Превью)', 'CheckBox (16x16, 32x32, 256x256)', 'Button (Собрать ICO)'],
    csharpSummary: 'Нарезка масштабированных слоев и сборка правильного бинарного заголовка ICO.',
    tags: ['ico', 'иконки', 'конвертер', 'png', 'windows'],
  },
  {
    id: 'tpl_37',
    num: 37,
    category: 'media',
    categoryTitle: '🎬 Мультимедиа и Графика',
    title: 'Ножницы (Скриншотер)',
    icon: '✂️',
    description: 'Выделение области экрана рамкой, копирование в буфер обмена и сохранение на диск.',
    controlsCount: 6,
    hasDatabase: false,
    controlsList: ['Button (Снимок)', 'PictureBox (Скриншот)', 'Button (В буфер)', 'Button (Сохранить)'],
    csharpSummary: 'Захват контекста экрана через Graphics.CopyFromScreen и экспорт в буфер Windows.',
    tags: ['скриншот', 'ножницы', 'экран', 'захват', 'снимок'],
  },
  {
    id: 'tpl_38',
    num: 38,
    category: 'media',
    categoryTitle: '🎬 Мультимедиа и Графика',
    title: 'Диктофон (Запись звука)',
    icon: '🎙️',
    description: 'Индикатор уровня громкости микрофона, запись, пауза, экспорт аудио в WAV/MP3.',
    controlsCount: 7,
    hasDatabase: false,
    controlsList: ['ProgressBar (Уровень звука)', 'Button (Запись)', 'Button (Стоп)', 'Label (Таймер)'],
    csharpSummary: 'Захват звукового потока с микрофона и потоковая запись в стандартный WAV файл.',
    tags: ['диктофон', 'микрофон', 'запись', 'звук', 'аудио'],
  },
  {
    id: 'tpl_39',
    num: 39,
    category: 'media',
    categoryTitle: '🎬 Мультимедиа и Графика',
    title: 'Генератор и сканер QR-кодов',
    icon: '📱',
    description: 'Ввод текста или ссылки, генерация красивого QR-кода с выбором цвета и сохранением.',
    controlsCount: 7,
    hasDatabase: false,
    controlsList: ['TextBox (Текст)', 'PictureBox (QR-код)', 'Button (Генерировать)', 'Button (Сохранить)'],
    csharpSummary: 'Кодирование текста в матрицу QR-кода с коррекцией ошибок и векторной отрисовкой.',
    tags: ['qr', 'штрихкод', 'генератор', 'коды', 'сканер'],
  },
  {
    id: 'tpl_40',
    num: 40,
    category: 'media',
    categoryTitle: '🎬 Мультимедиа и Графика',
    title: 'Экранная пипетка цветов',
    icon: '💧',
    description: 'Лупа пикселей под курсором в любой точке экрана, копирование цвета в HEX, RGB, HSL.',
    controlsCount: 7,
    hasDatabase: false,
    controlsList: ['PictureBox (Лупа)', 'Panel (Цвет)', 'TextBox (HEX: #3B82F6)', 'TextBox (RGB)'],
    csharpSummary: 'Считывание цвета пикселя с глобального контекста экрана через Win32 API GetPixel().',
    tags: ['пипетка', 'цвет', 'hex', 'rgb', 'дизайн'],
  },

  // 🌐 КАТЕГОРИЯ 5: СЕТИ, ИНТЕРНЕТ И API (41–50)
  {
    id: 'tpl_41',
    num: 41,
    category: 'network',
    categoryTitle: '🌐 Сети и API',
    title: 'Погодный информер (API)',
    icon: '⛅',
    description: 'Выбор города, температура, давление, влажность, иконка погоды и прогноз на 5 дней.',
    controlsCount: 8,
    hasDatabase: false,
    controlsList: ['TextBox (Город)', 'Button (Запрос)', 'Label (Температура)', 'PictureBox (Иконка)'],
    csharpSummary: 'Асинхронный HttpClient запрос к REST API погоды, десериализация JSON в объекты.',
    tags: ['погода', 'api', 'http', 'json', 'город'],
  },
  {
    id: 'tpl_42',
    num: 42,
    category: 'network',
    categoryTitle: '🌐 Сети и API',
    title: 'Крипто-трекер и валюты',
    icon: '🪙',
    description: 'Живой курс BTC, ETH, USD, EUR, график динамики изменения цен с автообновлением.',
    controlsCount: 8,
    hasDatabase: false,
    controlsList: ['DataGridView (Курсы)', 'DataChart (Динамика)', 'Label (BTC/USD)', 'Timer'],
    csharpSummary: 'Периодический опрос биржевого API через WebSocket/HTTP с отрисовкой графика котировок.',
    tags: ['крипта', 'btc', 'валюты', 'биржи', 'котировки'],
  },
  {
    id: 'tpl_43',
    num: 43,
    category: 'network',
    categoryTitle: '🌐 Сети и API',
    title: 'Панель Telegram-Бота',
    icon: '🤖',
    description: 'Рассылка сообщений в каналы, список подписчиков, просмотр входящих команд бота.',
    controlsCount: 7,
    hasDatabase: true,
    dbTableName: 'Subscribers',
    controlsList: ['TextBox (Токен)', 'TextBox (Сообщение)', 'Button (Разослать)', 'ListBox (Лог)'],
    csharpSummary: 'Отправка сообщений и медиа в Telegram Bot API через POST запросы с валидацией токена.',
    tags: ['telegram', 'бот', 'рассылка', 'api', 'чат'],
  },
  {
    id: 'tpl_44',
    num: 44,
    category: 'network',
    categoryTitle: '🌐 Сети и API',
    title: 'FTP Файловый менеджер',
    icon: '🗂️',
    description: 'Дерево папок сервера, список локальных файлов, шкала загрузки и скачивания.',
    controlsCount: 8,
    hasDatabase: false,
    controlsList: ['TreeView (Сервер)', 'ListBox (Локальные)', 'ProgressBar', 'Button (Загрузить)'],
    csharpSummary: 'Работа с FTP/SFTP протоколами через FtpWebRequest, навигация по каталогам.',
    tags: ['ftp', 'сервер', 'файлы', 'загрузка', 'сеть'],
  },
  {
    id: 'tpl_45',
    num: 45,
    category: 'network',
    categoryTitle: '🌐 Сети и API',
    title: 'Агрегатор новостей (RSS)',
    icon: '📰',
    description: 'Каталог новостных каналов, список заголовков, превью статьи и открытие в браузере.',
    controlsCount: 7,
    hasDatabase: false,
    controlsList: ['ListBox (Новости)', 'RichTextBox (Превью статьи)', 'Button (Обновить)', 'TextBox (URL)'],
    csharpSummary: 'Парсинг XML/RSS фидов новостных сайтов через SyndicationFeed и XDocument.',
    tags: ['rss', 'новости', 'лента', 'xml', 'интернет'],
  },
  {
    id: 'tpl_46',
    num: 46,
    category: 'network',
    categoryTitle: '🌐 Сети и API',
    title: 'SMTP Почтовый клиент',
    icon: '✉️',
    description: 'Поля: Кому, Тема, Тело письма, прикрепление файлов, настройка SMTP сервера.',
    controlsCount: 8,
    hasDatabase: false,
    controlsList: ['TextBox (Кому)', 'TextBox (Тема)', 'RichTextBox (Текст)', 'Button (Отправить)'],
    csharpSummary: 'Отправка почтовых сообщений через System.Net.Mail.SmtpClient с поддержкой SSL/TLS.',
    tags: ['email', 'почта', 'smtp', 'письма', 'рассылка'],
  },
  {
    id: 'tpl_47',
    num: 47,
    category: 'network',
    categoryTitle: '🌐 Сети и API',
    title: 'Тестер вебхуков и API (Postman)',
    icon: '⚡',
    description: 'Конструктор HTTP-запросов (GET, POST, Headers, Body), замер времени ответа и JSON вывод.',
    controlsCount: 9,
    hasDatabase: false,
    controlsList: ['ComboBox (Метод)', 'TextBox (URL)', 'RichTextBox (Body)', 'RichTextBox (Response)'],
    csharpSummary: 'Отправка произвольных HTTP запросов, форматирование JSON ответа с подсветкой синтаксиса.',
    tags: ['postman', 'http', 'api', 'rest', 'тестирование'],
  },
  {
    id: 'tpl_48',
    num: 48,
    category: 'network',
    categoryTitle: '🌐 Сети и API',
    title: 'WHOIS & DNS Чекер',
    icon: '🌐',
    description: 'Ввод доменного имени, вывод IP-адресов, DNS-записей (A, MX, TXT) и данных регистратора.',
    controlsCount: 6,
    hasDatabase: false,
    controlsList: ['TextBox (Домен)', 'Button (Проверить)', 'DataGridView (DNS записи)', 'RichTextBox'],
    csharpSummary: 'Запрос DNS записей через Dns.GetHostEntry и чтение WHOIS информации сервера.',
    tags: ['whois', 'dns', 'домен', 'сайт', 'сервер'],
  },
  {
    id: 'tpl_49',
    num: 49,
    category: 'network',
    categoryTitle: '🌐 Сети и API',
    title: 'Локальный файловый веб-сервер',
    icon: '🖥️',
    description: 'Запуск HTTP-сервера в 1 клик, раздача файлов по Wi-Fi и локальной сети для коллег.',
    controlsCount: 7,
    hasDatabase: false,
    controlsList: ['Button (Старт сервера)', 'TextBox (Порт: 8080)', 'ListBox (Лог запросов)', 'Label (IP)'],
    csharpSummary: 'Встроенный многопоточный HttpListener с раздачей статических файлов по HTTP протоколу.',
    tags: ['сервер', 'http', 'файлы', 'раздача', 'wifi'],
  },
  {
    id: 'tpl_50',
    num: 50,
    category: 'network',
    categoryTitle: '🌐 Сети и API',
    title: 'Сетевой P2P Чат (TCP Sockets)',
    icon: '💬',
    description: 'Мгновенный обмен сообщениями в локальной сети, список онлайн участников.',
    controlsCount: 8,
    hasDatabase: false,
    controlsList: ['ListBox (Чат)', 'TextBox (Сообщение)', 'Button (Отправить)', 'TextBox (IP собеседника)'],
    csharpSummary: 'Асинхронный обмен данными по протоколу TCP Sockets с фоновым слушателем TcpListener.',
    tags: ['чат', 'p2p', 'tcp', 'сокеты', 'общение'],
  },

  // 📝 КАТЕГОРИЯ 6: ТЕКСТ, ДОКУМЕНТЫ И РЕДАКТОРЫ (51–60)
  {
    id: 'tpl_51',
    num: 51,
    category: 'text',
    categoryTitle: '📝 Текст и Редакторы',
    title: 'Текстовый процессор Wordpad',
    icon: '📄',
    description: 'Панель форматирования шрифта (Bold, Italic), выравнивание, цвет текста, печать документа.',
    controlsCount: 11,
    hasDatabase: false,
    controlsList: ['ToolStrip (Форматирование)', 'RichTextBox', 'Button (Сохранить)', 'Button (Печать)'],
    csharpSummary: 'Работа с форматированным текстом RTF через RichTextBox.SelectionFont и диалоги печати.',
    tags: ['word', 'wordpad', 'текст', 'rtf', 'редактор'],
  },
  {
    id: 'tpl_52',
    num: 52,
    category: 'text',
    categoryTitle: '📝 Текст и Редакторы',
    title: 'Markdown редактор с превью',
    icon: '📑',
    description: 'Двухоконный редактор: слева Markdown (# Заголовок), справа живой рендеринг в HTML.',
    controlsCount: 6,
    hasDatabase: false,
    controlsList: ['TextBox (Markdown)', 'Panel (HTML Превью)', 'Button (Экспорт HTML)', 'Button (Копировать)'],
    csharpSummary: 'Трансляция синтаксиса Markdown (заголовки, списки, код, таблицы) в HTML на лету.',
    tags: ['markdown', 'html', 'превью', 'документы', 'текст'],
  },
  {
    id: 'tpl_53',
    num: 53,
    category: 'text',
    categoryTitle: '📝 Текст и Редакторы',
    title: 'Редактор таблиц CSV/Excel',
    icon: '📊',
    description: 'Сетка ячеек, добавление строк и столбцов, формулы суммирования и экспорт в .csv.',
    controlsCount: 7,
    hasDatabase: false,
    controlsList: ['DataGridView', 'Button (Открыть CSV)', 'Button (Сохранить)', 'Button (Сумма)'],
    csharpSummary: 'Построчный парсер и генератор CSV файлов с обработкой кавычек и разделителей.',
    tags: ['csv', 'excel', 'таблица', 'ячейки', 'экспорт'],
  },
  {
    id: 'tpl_54',
    num: 54,
    category: 'text',
    categoryTitle: '📝 Текст и Редакторы',
    title: 'JSON/XML Форматировщик',
    icon: '🌲',
    description: 'Превращение нечитаемого JSON в красивый отформатированный вид с отступами и деревом.',
    controlsCount: 6,
    hasDatabase: false,
    controlsList: ['RichTextBox (Входной JSON)', 'TreeView (Дерево)', 'Button (Форматировать)'],
    csharpSummary: 'Валидация синтаксиса JSON, красивое форматирование (Prettify) и построение дерева объектов.',
    tags: ['json', 'xml', 'форматирование', 'дерево', 'структура'],
  },
  {
    id: 'tpl_55',
    num: 55,
    category: 'text',
    categoryTitle: '📝 Текст и Редакторы',
    title: 'Сравнение текстов (Diff Viewer)',
    icon: '⚖️',
    description: 'Два окна текстов, подсветка добавленных, удаленных и измененных строк зеленым/красным.',
    controlsCount: 6,
    hasDatabase: false,
    controlsList: ['RichTextBox (Оригинал)', 'RichTextBox (Измененный)', 'Button (Сравнить)'],
    csharpSummary: 'Алгоритм поиска наибольшей общей подпоследовательности (LCS) для сравнения строк текста.',
    tags: ['diff', 'сравнение', 'текст', 'версии', 'изменения'],
  },
  {
    id: 'tpl_56',
    num: 56,
    category: 'text',
    categoryTitle: '📝 Текст и Редакторы',
    title: 'Счетчик слов и аналитика текста',
    icon: '🧮',
    description: 'Подсчет символов с пробелами и без, количество слов, предложений, время чтения.',
    controlsCount: 7,
    hasDatabase: false,
    controlsList: ['RichTextBox', 'Label (Символов: 1250)', 'Label (Слов: 180)', 'Label (Время: 2 мин)'],
    csharpSummary: 'Анализ плотности ключевых слов, расчет индекса удобочитаемости Флеша в реальном времени.',
    tags: ['слова', 'аналитика', 'символы', 'чтение', 'статистика'],
  },
  {
    id: 'tpl_57',
    num: 57,
    category: 'text',
    categoryTitle: '📝 Текст и Редакторы',
    title: 'Шифратор текста AES-256',
    icon: '🔒',
    description: 'Ввод секретного сообщения, ввод пароля шифрования, получение зашифрованной Base64 строки.',
    controlsCount: 7,
    hasDatabase: false,
    controlsList: ['RichTextBox (Исходный текст)', 'TextBox (Пароль)', 'RichTextBox (Зашифровано)', 'Button'],
    csharpSummary: 'Симметричное блочное шифрование AES-256 с формированием случайного вектора инициализации (IV).',
    tags: ['aes', 'шифрование', 'секрет', 'пароль', 'крипто'],
  },
  {
    id: 'tpl_58',
    num: 58,
    category: 'text',
    categoryTitle: '📝 Текст и Редакторы',
    title: 'Дневник заметок с тегами',
    icon: '📒',
    description: 'Календарь заметок, поиск по тегам (#идеи, #учеба), прикрепление файлов и автосохранение.',
    controlsCount: 8,
    hasDatabase: true,
    dbTableName: 'Notes',
    controlsList: ['ListBox (Заметки)', 'TextBox (Заголовок)', 'RichTextBox (Текст)', 'Button (Сохранить)'],
    csharpSummary: 'Сохранение заметок в локальную SQLite базу с полнотекстовым поиском и временными метками.',
    tags: ['заметки', 'дневник', 'теги', 'мысли', 'sqlite'],
  },
  {
    id: 'tpl_59',
    num: 59,
    category: 'text',
    categoryTitle: '📝 Текст и Редакторы',
    title: 'Генератор писем по шаблону',
    icon: '✉️',
    description: 'Шаблон документа с маркерами {Имя}, {Сумма}, таблица клиентов и пакетная генерация.',
    controlsCount: 7,
    hasDatabase: true,
    dbTableName: 'Templates',
    controlsList: ['DataGridView (Клиенты)', 'TextBox (Шаблон)', 'Button (Сгенерировать)', 'RichTextBox'],
    csharpSummary: 'Автоматическая подстановка полей из таблицы в текстовый шаблон с сохранением в файлы.',
    tags: ['шаблоны', 'письма', 'генератор', 'документы', 'автозамена'],
  },
  {
    id: 'tpl_60',
    num: 60,
    category: 'text',
    categoryTitle: '📝 Текст и Редакторы',
    title: 'Анализатор лог-файлов',
    icon: '📜',
    description: 'Фильтрация гигабайтных логов по уровням [ERROR], [WARN], поиск по дате и стектрейсу.',
    controlsCount: 7,
    hasDatabase: false,
    controlsList: ['DataGridView (События лога)', 'ComboBox (Уровень: Error)', 'TextBox (Фильтр)', 'Button'],
    csharpSummary: 'Быстрое потоковое чтение логов с использованием регулярных выражений и подсветкой ошибок.',
    tags: ['логи', 'логгер', 'error', 'поиск', 'сервер'],
  },

  // 🎮 КАТЕГОРИЯ 7: ИГРЫ, АРКАДЫ И СИМУЛЯТОРЫ (61–70)
  {
    id: 'tpl_61',
    num: 61,
    category: 'games',
    categoryTitle: '🎮 Игры и Аркады',
    title: 'Крестики-Нолики с ИИ',
    icon: '❌',
    description: 'Поле 3×3, выбор стороны (X/O), счетчик побед, умный компьютер с алгоритмом Минимакс.',
    controlsCount: 11,
    hasDatabase: false,
    controlsList: ['9x Button (Сетка 3×3)', 'Label (Счет X:O)', 'Button (Новая игра)'],
    csharpSummary: 'Алгоритм минимакс с гарантией победы или ничьей для ИИ и проверка линий победы.',
    tags: ['крестики-нолики', 'игра', 'ии', 'минимакс', 'логика'],
  },
  {
    id: 'tpl_62',
    num: 62,
    category: 'games',
    categoryTitle: '🎮 Игры и Аркады',
    title: 'Сапер (Classic Minesweeper)',
    icon: '💣',
    description: 'Сетка 9×9 кнопок, установка флажков правой кнопкой, счетчик мин и таймер времени.',
    controlsCount: 15,
    hasDatabase: false,
    controlsList: ['Panel (Поле 9×9)', 'Label (Осталось мин)', 'Label (Таймер)', 'Button (Смайлик)'],
    csharpSummary: 'Генерация минного поля с безопасным первым кликом, рекурсивное открытие пустых ячеек (Flood Fill).',
    tags: ['сапер', 'игра', 'мины', 'классика', 'аркада'],
  },
  {
    id: 'tpl_63',
    num: 63,
    category: 'games',
    categoryTitle: '🎮 Игры и Аркады',
    title: 'Змейка (Snake Arcade)',
    icon: '🐍',
    description: 'Классическая аркада на сетке таймера: управление стрелками, яблоки, рост хвоста и счет.',
    controlsCount: 5,
    hasDatabase: false,
    controlsList: ['PictureBox (Игровое поле)', 'Label (Счет: 0)', 'Button (Старт)', 'Timer (100ms)'],
    csharpSummary: 'Игровой цикл на Timer, очередь сегментов тела змейки, генерация бонусов и детекция коллизий.',
    tags: ['змейка', 'аркада', 'игра', 'ретро', 'таймер'],
  },
  {
    id: 'tpl_64',
    num: 64,
    category: 'games',
    categoryTitle: '🎮 Игры и Аркады',
    title: 'Пятнашки (15-Puzzle)',
    icon: '🧩',
    description: 'Сетка 16 кнопок с числами 1–15, перемешивание поля, проверка правильности сборки.',
    controlsCount: 18,
    hasDatabase: false,
    controlsList: ['16x Button (Костяшки)', 'Button (Перемешать)', 'Label (Количество ходов)'],
    csharpSummary: 'Проверка четности перестановок для гарантии решаемости расклада и логика сдвига плиток.',
    tags: ['пятнашки', 'головоломка', 'числа', 'логика', 'игра'],
  },
  {
    id: 'tpl_65',
    num: 65,
    category: 'games',
    categoryTitle: '🎮 Игры и Аркады',
    title: 'Морской Бой',
    icon: '🚢',
    description: 'Два поля 10×10 (Игрок и Компьютер), расстановка кораблей, выстрелы и учет попаданий.',
    controlsCount: 8,
    hasDatabase: false,
    controlsList: ['Panel (Поле Игрока)', 'Panel (Поле Врага)', 'Label (Статус)', 'Button (Новый бой)'],
    csharpSummary: 'Автоматическая расстановка 10 кораблей по правилам, ИИ со стратегией добивания раненых кораблей.',
    tags: ['морской бой', 'корабли', 'тактика', 'игра', 'ии'],
  },
  {
    id: 'tpl_66',
    num: 66,
    category: 'games',
    categoryTitle: '🎮 Игры и Аркады',
    title: 'Викторина "Миллионер"',
    icon: '💎',
    description: '15 вопросов с нарастающей сложностью, подсказки 50:50, звонок другу, несгораемые суммы.',
    controlsCount: 9,
    hasDatabase: true,
    dbTableName: 'Quiz',
    controlsList: ['Label (Вопрос)', '4x Button (Варианты)', 'ListBox (Дерево сумм)', 'Button (50:50)'],
    csharpSummary: 'База вопросов с градацией по уровням сложности, обработка подсказок и анимация выигрыша.',
    tags: ['викторина', 'миллионер', 'квиз', 'интеллект', 'игра'],
  },
  {
    id: 'tpl_67',
    num: 67,
    category: 'games',
    categoryTitle: '🎮 Игры и Аркады',
    title: 'Бросок игральных кубиков (Dice)',
    icon: '🎲',
    description: 'Анимация броска 2-5 игральных костей, подсчет очков, режим для двух игроков.',
    controlsCount: 7,
    hasDatabase: false,
    controlsList: ['PictureBox (Кубик 1)', 'PictureBox (Кубик 2)', 'Button (Бросить)', 'Label (Сумма)'],
    csharpSummary: 'Генерация псевдослучайных значений 1-6 с имитацией броска через быстрый таймер.',
    tags: ['кубики', 'кости', 'рандом', 'игра', 'азарт'],
  },
  {
    id: 'tpl_68',
    num: 68,
    category: 'games',
    categoryTitle: '🎮 Игры и Аркады',
    title: 'Текстовый RPG-квест',
    icon: '⚔️',
    description: 'Сюжетные развилки, инвентарь героя, характеристики (HP, Мана, Золото), выбор действий.',
    controlsCount: 8,
    hasDatabase: true,
    dbTableName: 'QuestStory',
    controlsList: ['RichTextBox (Сюжет)', 'ListBox (Инвентарь)', 'ProgressBar (HP)', '3x Button (Выбор)'],
    csharpSummary: 'Дерево графа диалогов и локаций, учет предметов в рюкзаке и боевка с монстрами.',
    tags: ['rpg', 'квест', 'текст', 'сюжет', 'игра'],
  },
  {
    id: 'tpl_69',
    num: 69,
    category: 'games',
    categoryTitle: '🎮 Игры и Аркады',
    title: 'Кликер (Cookie Clicker)',
    icon: '🍪',
    description: 'Большая кнопка клика, счетчик очков, магазин авто-кликеров, фабрик и апгрейдов.',
    controlsCount: 8,
    hasDatabase: false,
    controlsList: ['Button (Печенька)', 'Label (Баланс)', 'ListBox (Магазин)', 'Timer (Пассивный доход)'],
    csharpSummary: 'Расчет кликов в секунду (CPS), экспоненциальный рост цен на здания и автосохранение.',
    tags: ['кликер', 'cookie', 'idle', 'апгрейды', 'игра'],
  },
  {
    id: 'tpl_70',
    num: 70,
    category: 'games',
    categoryTitle: '🎮 Игры и Аркады',
    title: 'Парные карточки (Memory Game)',
    icon: '🎴',
    description: 'Сетка 16 закрытых карт, переворачивание, поиск одинаковых картинок на память.',
    controlsCount: 18,
    hasDatabase: false,
    controlsList: ['16x Button (Карты)', 'Label (Ходы: 0)', 'Button (Рестарт)', 'Timer'],
    csharpSummary: 'Рандомизация 8 пар картинок, таймер скрытия несовпавших карт и подсчет рекордного времени.',
    tags: ['memory', 'память', 'карточки', 'логика', 'игра'],
  },

  // 🔒 КАТЕГОРИЯ 8: БЕЗОПАСНОСТЬ И АВТОРИЗАЦИЯ (71–80)
  {
    id: 'tpl_71',
    num: 71,
    category: 'security',
    categoryTitle: '🔒 Безопасность',
    title: 'Форма входа с капчей (Captcha)',
    icon: '🔐',
    description: 'Логин, пароль, генерация искаженного изображения капчи, блокировка после 3 ошибок.',
    controlsCount: 8,
    hasDatabase: true,
    dbTableName: 'Users',
    controlsList: ['TextBox (Логин)', 'TextBox (Пароль)', 'PictureBox (Капча)', 'Button (Войти)'],
    csharpSummary: 'Генерация шума и искаженного текста капчи, блокировка попыток ввода на 60 секунд.',
    tags: ['авторизация', 'логин', 'капча', 'защита', 'безопасность'],
  },
  {
    id: 'tpl_72',
    num: 72,
    category: 'security',
    categoryTitle: '🔒 Безопасность',
    title: '2FA Аутентификатор (TOTP)',
    icon: '⏱️',
    description: 'Генератор и валидатор 6-значных одноразовых кодов с круговым таймером на 30 секунд.',
    controlsCount: 6,
    hasDatabase: false,
    controlsList: ['TextBox (Секретный ключ)', 'Label (Код: 849 201)', 'ProgressBar (30s)', 'Timer'],
    csharpSummary: 'Реализация алгоритма RFC 6238 TOTP на основе HMAC-SHA1 с проверкой временных окон.',
    tags: ['2fa', 'totp', 'аутентификация', 'безопасность', 'коды'],
  },
  {
    id: 'tpl_73',
    num: 73,
    category: 'security',
    categoryTitle: '🔒 Безопасность',
    title: 'Менеджер паролей (Сейф)',
    icon: '🗄️',
    description: 'Шифрованное хранилище аккаунтов, мастер-пароль, скрытие паролей за звездочками.',
    controlsCount: 8,
    hasDatabase: true,
    dbTableName: 'Vault',
    controlsList: ['DataGridView', 'TextBox (Сайт)', 'TextBox (Логин)', 'TextBox (Пароль)', 'Button'],
    csharpSummary: 'Шифрование всей базы паролей по алгоритму AES-256 с ключом на основе PBKDF2.',
    tags: ['пароли', 'сейф', 'хранилище', 'aes', 'крипто'],
  },
  {
    id: 'tpl_74',
    num: 74,
    category: 'security',
    categoryTitle: '🔒 Безопасность',
    title: 'Генератор лицензионных ключей',
    icon: '🔑',
    description: 'Создание серийных номеров формата XXXX-XXXX-XXXX-XXXX с проверкой валидности и срока.',
    controlsCount: 6,
    hasDatabase: false,
    controlsList: ['TextBox (Ключ)', 'Button (Сгенерировать)', 'Button (Проверить)', 'Label (Статус)'],
    csharpSummary: 'Алгоритм контрольной суммы ключа на основе алгоритма Луна и цифровой подписи RSA.',
    tags: ['лицензии', 'ключи', 'активация', 'защита', 'софт'],
  },
  {
    id: 'tpl_75',
    num: 75,
    category: 'security',
    categoryTitle: '🔒 Безопасность',
    title: 'Управление ролями пользователей (RBAC)',
    icon: '👥',
    description: 'Матрица прав: Администратор, Модератор, Гость. Скрытие кнопок в зависимости от роли.',
    controlsCount: 9,
    hasDatabase: true,
    dbTableName: 'Roles',
    controlsList: ['ComboBox (Выбор роли)', 'CheckedListBox (Права доступа)', 'Button (Применить)'],
    csharpSummary: 'Ролевая модель доступа (Role-Based Access Control) с динамическим отключением элементов UI.',
    tags: ['rbac', 'роли', 'права', 'админ', 'доступ'],
  },
  {
    id: 'tpl_76',
    num: 76,
    category: 'security',
    categoryTitle: '🔒 Безопасность',
    title: 'Мастер установки софта (Installer)',
    icon: '📦',
    description: 'Пошаговый визард: Приветствие ──► Лицензия ──► Выбор папки ──► Прогресс установки.',
    controlsCount: 9,
    hasDatabase: false,
    controlsList: ['TabControl (Шаги)', 'CheckBox (Принять лицензию)', 'ProgressBar', 'Button (Далее)'],
    csharpSummary: 'Пошаговая валидация каждого экрана установки программы с блокировкой кнопки Далее.',
    tags: ['установщик', 'installer', 'wizard', 'софт', 'инсталлятор'],
  },
  {
    id: 'tpl_77',
    num: 77,
    category: 'security',
    categoryTitle: '🔒 Безопасность',
    title: 'Экран блокировки по PIN-коду',
    icon: '🔢',
    description: 'Цифровая клавиатура 0–9, 4 кружочка индикатора ввода, мгновенный вход при правильном PIN.',
    controlsCount: 14,
    hasDatabase: false,
    controlsList: ['10x Button (Цифры 0-9)', 'Panel (4 индикатора)', 'Button (Очистить)'],
    csharpSummary: 'Обработка ввода 4-значного PIN кода с тактильной обратной связью и сбросом при ошибке.',
    tags: ['pin', 'блокировка', 'код', 'экран', 'безопасность'],
  },
  {
    id: 'tpl_78',
    num: 78,
    category: 'security',
    categoryTitle: '🔒 Безопасность',
    title: 'Анализатор надежности пароля',
    icon: '🛡️',
    description: 'Индикатор силы пароля (Слабый/Средний/Сложный), проверка словарей утекших паролей.',
    controlsCount: 6,
    hasDatabase: false,
    controlsList: ['TextBox (Пароль)', 'ProgressBar (Сила %)', 'Label (Советы)', 'ListBox (Проверки)'],
    csharpSummary: 'Проверка длины, наличия спецсимволов, цифр, регистра и отсутствия словарных слов.',
    tags: ['пароль', 'энтропия', 'проверка', 'надежность', 'безопасность'],
  },
  {
    id: 'tpl_79',
    num: 79,
    category: 'security',
    categoryTitle: '🔒 Безопасность',
    title: 'Шифратор файлов на диске',
    icon: '🔏',
    description: 'Выбор любого файла, шифрование в защищенный формат .locked с паролем пользователя.',
    controlsCount: 6,
    hasDatabase: false,
    controlsList: ['TextBox (Путь к файлу)', 'TextBox (Пароль)', 'Button (Зашифровать)', 'ProgressBar'],
    csharpSummary: 'Потоковое побайтовое шифрование файлов через CryptoStream без переполнения оперативной памяти.',
    tags: ['шифратор', 'файлы', 'crypto', 'защита', 'пароль'],
  },
  {
    id: 'tpl_80',
    num: 80,
    category: 'security',
    categoryTitle: '🔒 Безопасность',
    title: 'Контроль целостности файлов',
    icon: '🔍',
    description: 'Список критических системных файлов, сверка контрольных сумм и оповещение о подмене.',
    controlsCount: 7,
    hasDatabase: true,
    dbTableName: 'FileSignatures',
    controlsList: ['DataGridView (Файлы и Хеши)', 'Button (Сверить)', 'Label (Статус: ОК)'],
    csharpSummary: 'Сравнение эталонных SHA-256 сигнатур файлов с фактическими на диске для обнаружения вирусов.',
    tags: ['контроль', 'целостность', 'хеш', 'антивирус', 'безопасность'],
  },

  // 🤖 КАТЕГОРИЯ 9: АВТОМАТИЗАЦИЯ, БОТЫ И RPA (81–90)
  {
    id: 'tpl_81',
    num: 81,
    category: 'automation',
    categoryTitle: '🤖 Автоматизация и Боты',
    title: 'Автокликер мыши',
    icon: '🖱️',
    description: 'Настройка интервала кликов (мс), выбор кнопки (ЛКМ/ПКМ), горячие клавиши старт/стоп.',
    controlsCount: 7,
    hasDatabase: false,
    controlsList: ['NumericUpDown (Интервал мс)', 'RadioButton (ЛКМ/ПКМ)', 'Button (Старт F6)', 'Timer'],
    csharpSummary: 'Эмуляция нажатий мыши через Win32 API SendInput / mouse_event по таймеру высокой точности.',
    tags: ['автокликер', 'мышь', 'клики', 'автоматизация', 'игры'],
  },
  {
    id: 'tpl_82',
    num: 82,
    category: 'automation',
    categoryTitle: '🤖 Автоматизация и Боты',
    title: 'Планировщик задач (Cron Scheduler)',
    icon: '📅',
    description: 'Таблица расписания, запуск нужных программ и скриптов в заданное время.',
    controlsCount: 8,
    hasDatabase: true,
    dbTableName: 'ScheduledTasks',
    controlsList: ['DataGridView', 'DateTimePicker (Время)', 'TextBox (Путь к .exe)', 'Button (Добавить)'],
    csharpSummary: 'Фоновый планировщик на System.Threading.Timer с запуском процессов через Process.Start().',
    tags: ['планировщик', 'cron', 'автозапуск', 'задачи', 'таймер'],
  },
  {
    id: 'tpl_83',
    num: 83,
    category: 'automation',
    categoryTitle: '🤖 Автоматизация и Боты',
    title: 'Парсер картинок с веб-страниц',
    icon: '🖼️',
    description: 'Ввод URL сайта, извлечение всех ссылок на изображения, предпросмотр и пакетное скачивание.',
    controlsCount: 7,
    hasDatabase: false,
    controlsList: ['TextBox (URL)', 'Button (Спарсить)', 'ListBox (Найденные фото)', 'Button (Скачать все)'],
    csharpSummary: 'Парсинг тегов <img src="..."> с использованием регулярных выражений и асинхронная загрузка.',
    tags: ['парсер', 'картинки', 'веб', 'html', 'скачивание'],
  },
  {
    id: 'tpl_84',
    num: 84,
    category: 'automation',
    categoryTitle: '🤖 Автоматизация и Боты',
    title: 'Пакетный сжиматель фото',
    icon: '🗜️',
    description: 'Выбор папки с тяжелыми фотографиями, ползунок качества (1-100%), массовая компрессия.',
    controlsCount: 7,
    hasDatabase: false,
    controlsList: ['TrackBar (Качество)', 'ListBox (Файлы)', 'ProgressBar', 'Button (Сжать)'],
    csharpSummary: 'Массовое изменение разрешения и сжатие JPEG с помощью ImageCodecInfo и EncoderParameters.',
    tags: ['сжатие', 'фото', 'оптимизация', 'jpeg', 'пакетно'],
  },
  {
    id: 'tpl_85',
    num: 85,
    category: 'automation',
    categoryTitle: '🤖 Автоматизация и Боты',
    title: 'Генератор фейковых пользователей',
    icon: '👤',
    description: 'Генерация 1000 реалистичных тестовых данных (Имя, Фамилия, Телефон, Email, Город, Паспорт).',
    controlsCount: 7,
    hasDatabase: false,
    controlsList: ['NumericUpDown (Кол-во: 100)', 'DataGridView', 'Button (Сгенерировать)', 'Button (В CSV)'],
    csharpSummary: 'Рандомизатор на основе словарей русских/английских имен, генерация валидных телефонов и email.',
    tags: ['тестовые данные', 'фэйки', 'пользователи', 'генератор', 'база'],
  },
  {
    id: 'tpl_86',
    num: 86,
    category: 'automation',
    categoryTitle: '🤖 Автоматизация и Боты',
    title: 'Монитор доступности сайтов (Uptime)',
    icon: '🟢',
    description: 'Список серверов, статус (Онлайн/Офлайн), пинг, звуковое оповещение при падении сайта.',
    controlsCount: 8,
    hasDatabase: true,
    dbTableName: 'MonitoredHosts',
    controlsList: ['DataGridView (Серверы)', 'TextBox (URL)', 'Button (Добавить)', 'Timer (Опрос 10с)'],
    csharpSummary: 'Фоновая проверка HTTP кодов ответа 200 OK, замер времени отклика и ведение журнала сбоев.',
    tags: ['uptime', 'мониторинг', 'сайты', 'сервер', 'проверка'],
  },
  {
    id: 'tpl_87',
    num: 87,
    category: 'automation',
    categoryTitle: '🤖 Автоматизация и Боты',
    title: 'Авто-бэкап папок по расписанию',
    icon: '💾',
    description: 'Выбор папки-источника, интервал архивации, создание сжатых ZIP-архивов с датой в названии.',
    controlsCount: 7,
    hasDatabase: false,
    controlsList: ['TextBox (Откуда)', 'TextBox (Куда)', 'ComboBox (Каждые 60 мин)', 'Button (Архивировать)'],
    csharpSummary: 'Создание архивных копий каталогов через System.IO.Compression.ZipFile по таймеру.',
    tags: ['бэкап', 'zip', 'архив', 'резервное копирование', 'файлы'],
  },
  {
    id: 'tpl_88',
    num: 88,
    category: 'automation',
    categoryTitle: '🤖 Автоматизация и Боты',
    title: 'Макрос набора текста (Auto-Typer)',
    icon: '⌨️',
    description: 'Поле текста, задержка между нажатиями (мс), запуск авто-печати со скоростью человека.',
    controlsCount: 6,
    hasDatabase: false,
    controlsList: ['RichTextBox (Текст)', 'NumericUpDown (Задержка: 50мс)', 'Button (Старт)'],
    csharpSummary: 'Последовательная посимвольная отправка нажатий клавиш через SendKeys.SendWait().',
    tags: ['макрос', 'печать', 'клавиатура', 'автоматизация', 'бот'],
  },
  {
    id: 'tpl_89',
    num: 89,
    category: 'automation',
    categoryTitle: '🤖 Автоматизация и Боты',
    title: 'Трекер цен товаров в интернет-магазинах',
    icon: '🏷️',
    description: 'Ссылка на страницу товара, текущая цена, порог желаемой скидки, звуковой сигнал.',
    controlsCount: 8,
    hasDatabase: true,
    dbTableName: 'TrackedItems',
    controlsList: ['DataGridView', 'TextBox (URL товара)', 'NumericUpDown (Желаемая цена)', 'Button'],
    csharpSummary: 'Периодический скрейпинг ценника со страницы товара с оповещением при снижении цены.',
    tags: ['цены', 'скидки', 'магазины', 'парсинг', 'трекер'],
  },
  {
    id: 'tpl_90',
    num: 90,
    category: 'automation',
    categoryTitle: '🤖 Автоматизация и Боты',
    title: 'Менеджер истории буфера обмена',
    icon: '📋',
    description: 'Сохранение истории последних 30 скопированных текстов, быстрый поиск и вставка в 1 клик.',
    controlsCount: 6,
    hasDatabase: false,
    controlsList: ['ListBox (История)', 'TextBox (Поиск)', 'Button (Очистить)', 'Timer'],
    csharpSummary: 'Перехват содержимого Clipboard.GetText() при изменении буфера Windows.',
    tags: ['буфер обмена', 'clipboard', 'копирование', 'история', 'утилита'],
  },

  // ⚡️ КАТЕГОРИЯ 10: ИНЖЕНЕРИЯ, СХЕМОТЕХНИКА И IOT (91–100)
  {
    id: 'tpl_91',
    num: 91,
    category: 'iot',
    categoryTitle: '⚡️ Инженерия и IoT',
    title: 'COM-порт Терминал (Arduino / ESP32)',
    icon: '🔌',
    description: 'Выбор порта (COM3), скорость бод (9600–115200), отправка команд, живой лог данных.',
    controlsCount: 8,
    hasDatabase: false,
    controlsList: ['ComboBox (COM Порт)', 'ComboBox (Baud Rate)', 'RichTextBox (Лог)', 'Button (Подключить)'],
    csharpSummary: 'Асинхронное чтение и отправка байтов через System.IO.Ports.SerialPort в реальном времени.',
    tags: ['com-порт', 'arduino', 'esp32', 'serial', 'железо'],
  },
  {
    id: 'tpl_92',
    num: 92,
    category: 'iot',
    categoryTitle: '⚡️ Инженерия и IoT',
    title: 'Калькулятор цветных полос резисторов',
    icon: '🪡',
    description: 'Выбор 4 или 5 цветных полос на корпусе резистора, мгновенный расчет номинала в Омах.',
    controlsCount: 8,
    hasDatabase: false,
    controlsList: ['4x ComboBox (Полосы)', 'Panel (Вид резистора)', 'Label (Номинал: 4.7 кОм ±5%)'],
    csharpSummary: 'Табличный расчет номинального сопротивления резисторов по ГОСТ/EIA-96.',
    tags: ['резисторы', 'схемотехника', 'омы', 'электроника', 'инженерия'],
  },
  {
    id: 'tpl_93',
    num: 93,
    category: 'iot',
    categoryTitle: '⚡️ Инженерия и IoT',
    title: 'Калькулятор закона Ома',
    icon: '⚡',
    description: 'Поля: Напряжение (V), Ток (I), Сопротивление (R), Мощность (P). Расчет по двум известным.',
    controlsCount: 6,
    hasDatabase: false,
    controlsList: ['TextBox (U, Вольт)', 'TextBox (I, Ампер)', 'TextBox (R, Ом)', 'TextBox (P, Ватт)'],
    csharpSummary: 'Взаимный пересчет электрических величин по формулам V=I*R и P=V*I.',
    tags: ['закон ома', 'электрика', 'ватты', 'вольты', 'физика'],
  },
  {
    id: 'tpl_94',
    num: 94,
    category: 'iot',
    categoryTitle: '⚡️ Инженерия и IoT',
    title: 'Калькулятор ШИМ и таймера 555',
    icon: '⏲️',
    description: 'Выбор R1, R2, C1 для микросхемы NE555, расчет частоты (Гц), периода и скважности (%).',
    controlsCount: 7,
    hasDatabase: false,
    controlsList: ['NumericUpDown (R1)', 'NumericUpDown (R2)', 'NumericUpDown (C1)', 'Label (Частота Гц)'],
    csharpSummary: 'Формулы нестабильного мультивибратора на интегральном таймере 555.',
    tags: ['555', 'не555', 'шим', 'частота', 'электроника'],
  },
  {
    id: 'tpl_95',
    num: 95,
    category: 'iot',
    categoryTitle: '⚡️ Инженерия и IoT',
    title: 'Звуковой осциллограф',
    icon: '📉',
    description: 'График звуковой волны в реальном времени с микрофона, частота, амплитуда сигнала.',
    controlsCount: 6,
    hasDatabase: false,
    controlsList: ['PictureBox (Осциллограмма)', 'TrackBar (Развертка)', 'TrackBar (Усиление)', 'Timer'],
    csharpSummary: 'Отрисовка аудиоволны из буфера микрофона через быстрый массив точек Graphics.DrawLines.',
    tags: ['осциллограф', 'звук', 'волна', 'сигнал', 'инженерия'],
  },
  {
    id: 'tpl_96',
    num: 96,
    category: 'iot',
    categoryTitle: '⚡️ Инженерия и IoT',
    title: 'Телеметрия IoT датчиков (Дашборд)',
    icon: '🎛️',
    description: '4 круговых индикатора: Температура, Влажность, Давление, CO2 со сменой цвета при опасности.',
    controlsCount: 8,
    hasDatabase: true,
    dbTableName: 'SensorLogs',
    controlsList: ['4x Panel (Стрелочные шкалы)', 'DataGridView (История)', 'Timer (Опрос)'],
    csharpSummary: 'Прием телеметрии IoT устройств по MQTT/HTTP с записью в базу и алертом при перегреве.',
    tags: ['iot', 'датчики', 'температура', 'телеметрия', 'дашборд'],
  },
  {
    id: 'tpl_97',
    num: 97,
    category: 'iot',
    categoryTitle: '⚡️ Инженерия и IoT',
    title: 'Инженерный конвертер физических величин',
    icon: '📏',
    description: 'Длина (м, фут, дюйм), Масса (кг, фунт), Давление (Па, бар, psi, мм рт. ст.), Температура.',
    controlsCount: 7,
    hasDatabase: false,
    controlsList: ['ComboBox (Категория)', 'TextBox (Вход)', 'ComboBox (Из)', 'TextBox (Выход)', 'ComboBox (В)'],
    csharpSummary: 'Матрица точных физических коэффициентов пересчета системы СИ и имперских единиц.',
    tags: ['конвертер', 'величины', 'дюймы', 'паскали', 'физика'],
  },
  {
    id: 'tpl_98',
    num: 98,
    category: 'iot',
    categoryTitle: '⚡️ Инженерия и IoT',
    title: 'Расчет сечения электрического кабеля',
    icon: '🔌',
    description: 'Мощность нагрузки (кВт), длина линии, материал (медь/алюминий), 220В/380В, расчет сечения.',
    controlsCount: 8,
    hasDatabase: false,
    controlsList: ['NumericUpDown (Мощность кВт)', 'NumericUpDown (Длина м)', 'ComboBox (Медь/Алюм)', 'Label'],
    csharpSummary: 'Расчет допустимого длительного тока по ПУЭ и падения напряжения в кабельной линии.',
    tags: ['кабель', 'электрика', 'сечение', 'проводка', 'расчет'],
  },
  {
    id: 'tpl_99',
    num: 99,
    category: 'iot',
    categoryTitle: '⚡️ Инженерия и IoT',
    title: 'Симулятор перекрестка и светофора',
    icon: '🚦',
    description: '3 цветных сигнала (Красный, Желтый, Зеленый), режим пешеходного перехода, таймер фаз.',
    controlsCount: 7,
    hasDatabase: false,
    controlsList: ['Panel (Светофор)', 'Button (Кнопка пешехода)', 'Label (Таймер)', 'Timer (Переключение)'],
    csharpSummary: 'Конечный автомат (State Machine) управления фазами перекрестка с логикой приоритета.',
    tags: ['светофор', 'автомат', 'симуляция', 'таймер', 'дорога'],
  },
  {
    id: 'tpl_100',
    num: 100,
    category: 'iot',
    categoryTitle: '⚡️ Инженерия и IoT',
    title: 'GPS NMEA Парсер трека',
    icon: '🛰️',
    description: 'Поле сырых данных $GPRMC, спидометр, широта, долгота, курс и экспорт координат в KML.',
    controlsCount: 7,
    hasDatabase: false,
    controlsList: ['TextBox (NMEA строка)', 'Label (Широта)', 'Label (Долгота)', 'Label (Скорость км/ч)'],
    csharpSummary: 'Парсер стандартных GPS строк $GPGGA/$GPRMC с пересчетом узлов в км/ч и валидацией контрольной суммы.',
    tags: ['gps', 'nmea', 'координаты', 'спутники', 'навигация'],
  },
];

const createNode = (
  id: string,
  type: ControlType,
  bounds: { x: number; y: number; width: number; height: number },
  props: Record<string, any> & { name: string },
  events: Record<string, string> = {},
  parentId: string | null = null,
  childrenIds: string[] = []
): DesignerNode => ({
  id,
  type,
  bounds,
  properties: {
    enabled: true,
    visible: true,
    ...props,
  } as NodeProperties,
  events,
  parentId,
  childrenIds,
});

/**
 * Factory that generates a complete DesignerProjectState for any of the 100 templates
 */
export const instantiateTemplateProject = (templateId: string): DesignerProjectState => {
  const tpl = TEMPLATES_CATALOG.find((t) => t.id === templateId) || TEMPLATES_CATALOG[0];
  const rootId = `form_${tpl.id}`;
  const formName = `Main${tpl.title.replace(/[^a-zA-Z0-9а-яА-Я]/g, '')}Form`;

  // Base Form
  const rootForm = createNode(
    rootId,
    'Form',
    { x: 0, y: 0, width: 720, height: 520 },
    {
      name: formName,
      text: `${tpl.icon} ${tpl.title} - NextGen C# IDE`,
      backColor: '#18181B',
      foreColor: '#F4F4F5',
      fontFamily: 'Segoe UI',
      fontSize: 9,
    },
    { Load: `${formName}_Load` }
  );

  const nodes: Record<string, DesignerNode> = {
    [rootId]: rootForm,
  };

  const childIds: string[] = [];

  // 1. Header Banner Panel
  const headerId = `pnlHeader_${tpl.id}`;
  nodes[headerId] = createNode(
    headerId,
    'Panel',
    { x: 16, y: 16, width: 688, height: 60 },
    {
      name: `pnlHeader`,
      backColor: '#27272A',
      foreColor: '#FFFFFF',
      borderStyle: 'FixedSingle',
    },
    {},
    rootId,
    [`lblTitle_${tpl.id}`, `lblDesc_${tpl.id}`]
  );
  childIds.push(headerId);

  // Header Title
  nodes[`lblTitle_${tpl.id}`] = createNode(
    `lblTitle_${tpl.id}`,
    'Label',
    { x: 16, y: 8, width: 500, height: 24 },
    {
      name: 'lblTitle',
      text: `${tpl.icon} ${tpl.title}`,
      fontSize: 12,
      fontBold: true,
      foreColor: '#60A5FA',
    },
    {},
    headerId
  );

  // Header Subtitle
  nodes[`lblDesc_${tpl.id}`] = createNode(
    `lblDesc_${tpl.id}`,
    'Label',
    { x: 16, y: 34, width: 650, height: 18 },
    {
      name: 'lblDescription',
      text: tpl.description,
      fontSize: 9,
      foreColor: '#A1A1AA',
    },
    {},
    headerId
  );

  // 2. Main Content Area depending on template characteristics
  if (tpl.hasDatabase || tpl.category === 'business') {
    // DataGridView + Controls layout
    const gridId = `dgvMain_${tpl.id}`;
    nodes[gridId] = createNode(
      gridId,
      'DataGridView',
      { x: 16, y: 90, width: 480, height: 360 },
      {
        name: 'dgvItems',
        backColor: '#09090B',
        foreColor: '#FAFAFA',
      },
      { SelectionChanged: 'dgvItems_SelectionChanged' },
      rootId
    );
    childIds.push(gridId);

    // Right Action Panel
    const rightPnlId = `pnlActions_${tpl.id}`;
    nodes[rightPnlId] = createNode(
      rightPnlId,
      'GroupBox',
      { x: 510, y: 90, width: 194, height: 360 },
      {
        name: 'grpActions',
        text: '⚙️ Управление',
        backColor: '#27272A',
        foreColor: '#E4E4E7',
      },
      {},
      rootId,
      [`btnActionAdd_${tpl.id}`, `btnActionDel_${tpl.id}`, `btnActionSave_${tpl.id}`]
    );
    childIds.push(rightPnlId);

    nodes[`btnActionAdd_${tpl.id}`] = createNode(
      `btnActionAdd_${tpl.id}`,
      'Button',
      { x: 16, y: 30, width: 160, height: 36 },
      {
        name: 'btnAdd',
        text: '➕ Добавить запись',
        backColor: '#2563EB',
        foreColor: '#FFFFFF',
        fontBold: true,
      },
      { Click: 'btnAdd_Click' },
      rightPnlId
    );

    nodes[`btnActionDel_${tpl.id}`] = createNode(
      `btnActionDel_${tpl.id}`,
      'Button',
      { x: 16, y: 78, width: 160, height: 36 },
      {
        name: 'btnDelete',
        text: '🗑 Удалить запись',
        backColor: '#DC2626',
        foreColor: '#FFFFFF',
      },
      { Click: 'btnDelete_Click' },
      rightPnlId
    );

    nodes[`btnActionSave_${tpl.id}`] = createNode(
      `btnActionSave_${tpl.id}`,
      'Button',
      { x: 16, y: 126, width: 160, height: 36 },
      {
        name: 'btnExport',
        text: '💾 Экспорт в файл',
        backColor: '#059669',
        foreColor: '#FFFFFF',
      },
      { Click: 'btnExport_Click' },
      rightPnlId
    );
  } else if (tpl.category === 'games') {
    // Game Area with Center Canvas / Buttons
    const gamePnlId = `pnlGame_${tpl.id}`;
    nodes[gamePnlId] = createNode(
      gamePnlId,
      'Panel',
      { x: 16, y: 90, width: 480, height: 360 },
      {
        name: 'pnlGameField',
        backColor: '#09090B',
        foreColor: '#FFFFFF',
        borderStyle: 'FixedSingle',
      },
      {},
      rootId,
      [`btnGameAction1_${tpl.id}`, `btnGameAction2_${tpl.id}`, `lblGameScore_${tpl.id}`]
    );
    childIds.push(gamePnlId);

    nodes[`lblGameScore_${tpl.id}`] = createNode(
      `lblGameScore_${tpl.id}`,
      'Label',
      { x: 16, y: 16, width: 440, height: 32 },
      {
        name: 'lblScore',
        text: '🏆 СЧЕТ: 0  |  ЖИЗНИ: ❤️❤️❤️',
        fontSize: 14,
        fontBold: true,
        foreColor: '#FBBF24',
      },
      {},
      gamePnlId
    );

    nodes[`btnGameAction1_${tpl.id}`] = createNode(
      `btnGameAction1_${tpl.id}`,
      'Button',
      { x: 140, y: 130, width: 200, height: 50 },
      {
        name: 'btnStartGame',
        text: '🎮 НАЧАТЬ ИГРУ',
        backColor: '#10B981',
        foreColor: '#FFFFFF',
        fontBold: true,
        fontSize: 12,
      },
      { Click: 'btnStartGame_Click' },
      gamePnlId
    );

    nodes[`btnGameAction2_${tpl.id}`] = createNode(
      `btnGameAction2_${tpl.id}`,
      'Button',
      { x: 140, y: 195, width: 200, height: 40 },
      {
        name: 'btnRestart',
        text: '🔄 Перезапустить',
        backColor: '#3F3F46',
        foreColor: '#E4E4E7',
      },
      { Click: 'btnRestart_Click' },
      gamePnlId
    );

    // Right Stats Panel
    const statsId = `grpStats_${tpl.id}`;
    nodes[statsId] = createNode(
      statsId,
      'GroupBox',
      { x: 510, y: 90, width: 194, height: 360 },
      {
        name: 'grpStats',
        text: '📊 Рекорды и Настройки',
        backColor: '#27272A',
        foreColor: '#E4E4E7',
      },
      {},
      rootId
    );
    childIds.push(statsId);
  } else {
    // Standard Utility Layout: Inputs + Calculation Buttons + Output Display
    const inputPnlId = `grpInputs_${tpl.id}`;
    nodes[inputPnlId] = createNode(
      inputPnlId,
      'GroupBox',
      { x: 16, y: 90, width: 330, height: 360 },
      {
        name: 'grpInputData',
        text: '📥 Входные параметры',
        backColor: '#27272A',
        foreColor: '#E4E4E7',
      },
      {},
      rootId,
      [`txtInput1_${tpl.id}`, `txtInput2_${tpl.id}`, `btnCalc_${tpl.id}`]
    );
    childIds.push(inputPnlId);

    nodes[`txtInput1_${tpl.id}`] = createNode(
      `txtInput1_${tpl.id}`,
      'TextBox',
      { x: 20, y: 40, width: 290, height: 36 },
      {
        name: 'txtInputA',
        text: '100',
        backColor: '#18181B',
        foreColor: '#FFFFFF',
      },
      {},
      inputPnlId
    );

    nodes[`txtInput2_${tpl.id}`] = createNode(
      `txtInput2_${tpl.id}`,
      'TextBox',
      { x: 20, y: 90, width: 290, height: 36 },
      {
        name: 'txtInputB',
        text: '25',
        backColor: '#18181B',
        foreColor: '#FFFFFF',
      },
      {},
      inputPnlId
    );

    nodes[`btnCalc_${tpl.id}`] = createNode(
      `btnCalc_${tpl.id}`,
      'Button',
      { x: 20, y: 150, width: 290, height: 42 },
      {
        name: 'btnCalculate',
        text: '⚡️ Выполнить расчет',
        backColor: '#2563EB',
        foreColor: '#FFFFFF',
        fontBold: true,
      },
      { Click: 'btnCalculate_Click' },
      inputPnlId
    );

    // Output Display Panel
    const outputPnlId = `grpOutput_${tpl.id}`;
    nodes[outputPnlId] = createNode(
      outputPnlId,
      'GroupBox',
      { x: 360, y: 90, width: 344, height: 360 },
      {
        name: 'grpResult',
        text: '📤 Результаты вычислений',
        backColor: '#27272A',
        foreColor: '#E4E4E7',
      },
      {},
      rootId,
      [`txtResult_${tpl.id}`]
    );
    childIds.push(outputPnlId);

    nodes[`txtResult_${tpl.id}`] = createNode(
      `txtResult_${tpl.id}`,
      'RichTextBox',
      { x: 16, y: 30, width: 312, height: 310 },
      {
        name: 'txtResultLog',
        text: `Готов к работе.\nШаблон: ${tpl.title}\nКатегория: ${tpl.categoryTitle}\nЛогика: ${tpl.csharpSummary}`,
        backColor: '#09090B',
        foreColor: '#34D399',
        fontFamily: 'Consolas',
      },
      {},
      outputPnlId
    );
  }

  // Footer Status Bar
  const statusId = `lblStatus_${tpl.id}`;
  nodes[statusId] = createNode(
    statusId,
    'Label',
    { x: 16, y: 465, width: 688, height: 20 },
    {
      name: 'lblStatus',
      text: `🟢 Готов | .NET 8 WinForms | Шаблон #${tpl.num}: ${tpl.title}`,
      fontSize: 8,
      foreColor: '#71717A',
    },
    {},
    rootId
  );
  childIds.push(statusId);

  // Ensure all node properties have required fields (enabled, visible)
  Object.values(nodes).forEach((node) => {
    if (node.properties.enabled === undefined) node.properties.enabled = true;
    if (node.properties.visible === undefined) node.properties.visible = true;
  });

  rootForm.childrenIds = childIds;

  return {
    version: '1.0.0',
    projectName: tpl.title.replace(/[^a-zA-Z0-9]/g, '') || `Project_${tpl.id}`,
    rootFormId: rootId,
    nodes,
    selectedNodeIds: [rootId],
    targetFramework: 'WinForms',
    templateId: tpl.id,
  };
};
