import { DesignerProjectState, DesignerNode } from '../types/ast';

export const createEmptyProject = (): DesignerProjectState => {
  const rootId = 'form_root';
  const rootForm: DesignerNode = {
    id: rootId,
    type: 'Form',
    bounds: { x: 0, y: 0, width: 640, height: 480 },
    properties: {
      name: 'Form1',
      text: 'Form1',
      enabled: true,
      visible: true,
      backColor: '#FFFFFF',
      foreColor: '#18181B',
      fontFamily: 'Segoe UI',
      fontSize: 9,
    },
    events: {
      Load: 'Form1_Load',
    },
    parentId: null,
    childrenIds: [],
  };

  return {
    version: '1.0.0',
    projectName: 'WinFormsApp1',
    rootFormId: rootId,
    nodes: {
      [rootId]: rootForm,
    },
    selectedNodeIds: [rootId],
    targetFramework: 'WinForms',
  };
};

export const createLoginTemplate = (): DesignerProjectState => {
  const rootId = 'form_login';

  const nodes: Record<string, DesignerNode> = {
    [rootId]: {
      id: rootId,
      type: 'Form',
      bounds: { x: 0, y: 0, width: 440, height: 380 },
      properties: {
        name: 'LoginForm',
        text: 'Авторизация в системе',
        enabled: true,
        visible: true,
        backColor: '#F8FAFC',
        foreColor: '#0F172A',
        fontFamily: 'Segoe UI',
        fontSize: 9,
      },
      events: {
        Load: 'LoginForm_Load',
      },
      parentId: null,
      childrenIds: ['lblHeader', 'lblDesc', 'lblUser', 'txtUser', 'lblPass', 'txtPass', 'chkRemember', 'btnSubmit', 'btnCancel'],
    },
    lblHeader: {
      id: 'lblHeader',
      type: 'Label',
      bounds: { x: 40, y: 30, width: 260, height: 28 },
      properties: {
        name: 'lblHeader',
        text: 'Добро пожаловать',
        enabled: true,
        visible: true,
        fontSize: 14,
        fontBold: true,
        foreColor: '#0F172A',
      },
      events: {},
      parentId: rootId,
      childrenIds: [],
    },
    lblDesc: {
      id: 'lblDesc',
      type: 'Label',
      bounds: { x: 40, y: 62, width: 340, height: 20 },
      properties: {
        name: 'lblDesc',
        text: 'Введите учетные данные для продолжения работы',
        enabled: true,
        visible: true,
        fontSize: 9,
        foreColor: '#64748B',
      },
      events: {},
      parentId: rootId,
      childrenIds: [],
    },
    lblUser: {
      id: 'lblUser',
      type: 'Label',
      bounds: { x: 40, y: 105, width: 100, height: 18 },
      properties: {
        name: 'lblUser',
        text: 'Имя пользователя:',
        enabled: true,
        visible: true,
        fontBold: true,
        foreColor: '#334155',
      },
      events: {},
      parentId: rootId,
      childrenIds: [],
    },
    txtUser: {
      id: 'txtUser',
      type: 'TextBox',
      bounds: { x: 40, y: 128, width: 350, height: 34 },
      properties: {
        name: 'txtUsername',
        text: 'administrator',
        placeholder: 'Введите логин...',
        enabled: true,
        visible: true,
        tabIndex: 1,
        backColor: '#FFFFFF',
      },
      events: {
        TextChanged: 'txtUsername_TextChanged',
      },
      parentId: rootId,
      childrenIds: [],
    },
    lblPass: {
      id: 'lblPass',
      type: 'Label',
      bounds: { x: 40, y: 175, width: 100, height: 18 },
      properties: {
        name: 'lblPass',
        text: 'Пароль:',
        enabled: true,
        visible: true,
        fontBold: true,
        foreColor: '#334155',
      },
      events: {},
      parentId: rootId,
      childrenIds: [],
    },
    txtPass: {
      id: 'txtPass',
      type: 'TextBox',
      bounds: { x: 40, y: 198, width: 350, height: 34 },
      properties: {
        name: 'txtPassword',
        text: '••••••••••••',
        placeholder: 'Введите пароль...',
        enabled: true,
        visible: true,
        tabIndex: 2,
        backColor: '#FFFFFF',
      },
      events: {},
      parentId: rootId,
      childrenIds: [],
    },
    chkRemember: {
      id: 'chkRemember',
      type: 'CheckBox',
      bounds: { x: 40, y: 248, width: 180, height: 24 },
      properties: {
        name: 'chkRememberMe',
        text: 'Запомнить меня на этом ПК',
        enabled: true,
        visible: true,
        checked: true,
        tabIndex: 3,
      },
      events: {
        CheckedChanged: 'chkRememberMe_CheckedChanged',
      },
      parentId: rootId,
      childrenIds: [],
    },
    btnSubmit: {
      id: 'btnSubmit',
      type: 'Button',
      bounds: { x: 230, y: 295, width: 160, height: 38 },
      properties: {
        name: 'btnSubmit',
        text: 'Войти в аккаунт',
        enabled: true,
        visible: true,
        backColor: '#2563EB',
        foreColor: '#FFFFFF',
        fontBold: true,
        tabIndex: 4,
      },
      events: {
        Click: 'btnSubmit_Click',
      },
      parentId: rootId,
      childrenIds: [],
    },
    btnCancel: {
      id: 'btnCancel',
      type: 'Button',
      bounds: { x: 120, y: 295, width: 100, height: 38 },
      properties: {
        name: 'btnCancel',
        text: 'Отмена',
        enabled: true,
        visible: true,
        backColor: '#E2E8F0',
        foreColor: '#1E293B',
        tabIndex: 5,
      },
      events: {
        Click: 'btnCancel_Click',
      },
      parentId: rootId,
      childrenIds: [],
    },
  };

  return {
    version: '1.0.0',
    projectName: 'LoginModule',
    rootFormId: rootId,
    nodes,
    selectedNodeIds: ['btnSubmit'],
    targetFramework: 'WinForms',
  };
};

export const createDashboardTemplate = (): DesignerProjectState => {
  const rootId = 'form_dashboard';

  const nodes: Record<string, DesignerNode> = {
    [rootId]: {
      id: rootId,
      type: 'Form',
      bounds: { x: 0, y: 0, width: 720, height: 480 },
      properties: {
        name: 'MainDashboard',
        text: 'Панель управления системой v2.4',
        enabled: true,
        visible: true,
        backColor: '#F1F5F9',
        foreColor: '#0F172A',
        fontFamily: 'Segoe UI',
        fontSize: 9,
      },
      events: {
        Load: 'MainDashboard_Load',
      },
      parentId: null,
      childrenIds: ['sidebarPanel', 'topPanel', 'card1', 'card2', 'panelTable'],
    },
    sidebarPanel: {
      id: 'sidebarPanel',
      type: 'Panel',
      bounds: { x: 0, y: 0, width: 180, height: 480 },
      properties: {
        name: 'panelSidebar',
        enabled: true,
        visible: true,
        backColor: '#0F172A',
        dock: 'Left',
      },
      events: {},
      parentId: rootId,
      childrenIds: ['lblLogo', 'btnNavOverview', 'btnNavUsers', 'btnNavReports', 'btnNavSettings'],
    },
    lblLogo: {
      id: 'lblLogo',
      type: 'Label',
      bounds: { x: 20, y: 22, width: 140, height: 26 },
      properties: {
        name: 'lblBrand',
        text: '⚡️ Enterprise UI',
        enabled: true,
        visible: true,
        fontSize: 11,
        fontBold: true,
        foreColor: '#FFFFFF',
      },
      events: {},
      parentId: 'sidebarPanel',
      childrenIds: [],
    },
    btnNavOverview: {
      id: 'btnNavOverview',
      type: 'Button',
      bounds: { x: 12, y: 70, width: 156, height: 34 },
      properties: {
        name: 'btnNavOverview',
        text: '📊 Сводка данных',
        enabled: true,
        visible: true,
        backColor: '#1E293B',
        foreColor: '#F8FAFC',
      },
      events: { Click: 'btnNavOverview_Click' },
      parentId: 'sidebarPanel',
      childrenIds: [],
    },
    btnNavUsers: {
      id: 'btnNavUsers',
      type: 'Button',
      bounds: { x: 12, y: 112, width: 156, height: 34 },
      properties: {
        name: 'btnNavUsers',
        text: '👥 Пользователи',
        enabled: true,
        visible: true,
        backColor: '#0F172A',
        foreColor: '#94A3B8',
      },
      events: { Click: 'btnNavUsers_Click' },
      parentId: 'sidebarPanel',
      childrenIds: [],
    },
    btnNavReports: {
      id: 'btnNavReports',
      type: 'Button',
      bounds: { x: 12, y: 154, width: 156, height: 34 },
      properties: {
        name: 'btnNavReports',
        text: '📑 Отчеты и логи',
        enabled: true,
        visible: true,
        backColor: '#0F172A',
        foreColor: '#94A3B8',
      },
      events: { Click: 'btnNavReports_Click' },
      parentId: 'sidebarPanel',
      childrenIds: [],
    },
    btnNavSettings: {
      id: 'btnNavSettings',
      type: 'Button',
      bounds: { x: 12, y: 420, width: 156, height: 34 },
      properties: {
        name: 'btnNavSettings',
        text: '⚙️ Настройки',
        enabled: true,
        visible: true,
        backColor: '#0F172A',
        foreColor: '#94A3B8',
        anchor: ['Bottom', 'Left'],
      },
      events: { Click: 'btnNavSettings_Click' },
      parentId: 'sidebarPanel',
      childrenIds: [],
    },
    topPanel: {
      id: 'topPanel',
      type: 'Panel',
      bounds: { x: 180, y: 0, width: 540, height: 56 },
      properties: {
        name: 'panelTopHeader',
        enabled: true,
        visible: true,
        backColor: '#FFFFFF',
        dock: 'Top',
      },
      events: {},
      parentId: rootId,
      childrenIds: ['txtSearch', 'btnRefresh'],
    },
    txtSearch: {
      id: 'txtSearch',
      type: 'TextBox',
      bounds: { x: 20, y: 12, width: 280, height: 32 },
      properties: {
        name: 'txtSearchQuery',
        placeholder: 'Поиск по записям и клиентам...',
        enabled: true,
        visible: true,
        backColor: '#F8FAFC',
      },
      events: { TextChanged: 'txtSearchQuery_TextChanged' },
      parentId: 'topPanel',
      childrenIds: [],
    },
    btnRefresh: {
      id: 'btnRefresh',
      type: 'Button',
      bounds: { x: 420, y: 12, width: 100, height: 32 },
      properties: {
        name: 'btnRefreshData',
        text: 'Обновить',
        enabled: true,
        visible: true,
        backColor: '#0284C7',
        foreColor: '#FFFFFF',
        anchor: ['Top', 'Right'],
      },
      events: { Click: 'btnRefreshData_Click' },
      parentId: 'topPanel',
      childrenIds: [],
    },
    card1: {
      id: 'card1',
      type: 'GroupBox',
      bounds: { x: 200, y: 76, width: 240, height: 110 },
      properties: {
        name: 'grpStatsRevenue',
        text: 'Выручка за месяц',
        enabled: true,
        visible: true,
        backColor: '#FFFFFF',
        fontBold: true,
      },
      events: {},
      parentId: rootId,
      childrenIds: ['lblStat1Val', 'lblStat1Sub'],
    },
    lblStat1Val: {
      id: 'lblStat1Val',
      type: 'Label',
      bounds: { x: 16, y: 28, width: 200, height: 34 },
      properties: {
        name: 'lblRevenueValue',
        text: '₽ 2,845,900',
        enabled: true,
        visible: true,
        fontSize: 16,
        fontBold: true,
        foreColor: '#059669',
      },
      events: {},
      parentId: 'card1',
      childrenIds: [],
    },
    lblStat1Sub: {
      id: 'lblStat1Sub',
      type: 'Label',
      bounds: { x: 16, y: 68, width: 200, height: 20 },
      properties: {
        name: 'lblRevenueChange',
        text: '▲ +14.2% по сравнению с прошлым мес.',
        enabled: true,
        visible: true,
        fontSize: 8,
        foreColor: '#64748B',
      },
      events: {},
      parentId: 'card1',
      childrenIds: [],
    },
    card2: {
      id: 'card2',
      type: 'GroupBox',
      bounds: { x: 460, y: 76, width: 240, height: 110 },
      properties: {
        name: 'grpStatsUsers',
        text: 'Активные сессии',
        enabled: true,
        visible: true,
        backColor: '#FFFFFF',
        fontBold: true,
      },
      events: {},
      parentId: rootId,
      childrenIds: ['lblStat2Val', 'progressBar1'],
    },
    lblStat2Val: {
      id: 'lblStat2Val',
      type: 'Label',
      bounds: { x: 16, y: 28, width: 200, height: 34 },
      properties: {
        name: 'lblActiveUsersCount',
        text: '1,420 онлайн',
        enabled: true,
        visible: true,
        fontSize: 15,
        fontBold: true,
        foreColor: '#0284C7',
      },
      events: {},
      parentId: 'card2',
      childrenIds: [],
    },
    progressBar1: {
      id: 'progressBar1',
      type: 'ProgressBar',
      bounds: { x: 16, y: 72, width: 208, height: 18 },
      properties: {
        name: 'progressServerLoad',
        progressValue: 74,
        enabled: true,
        visible: true,
      },
      events: {},
      parentId: 'card2',
      childrenIds: [],
    },
    panelTable: {
      id: 'panelTable',
      type: 'GroupBox',
      bounds: { x: 200, y: 206, width: 500, height: 250 },
      properties: {
        name: 'grpRecentActivity',
        text: 'Последние операции клиентов',
        enabled: true,
        visible: true,
        backColor: '#FFFFFF',
        fontBold: true,
        anchor: ['Top', 'Bottom', 'Left', 'Right'],
      },
      events: {},
      parentId: rootId,
      childrenIds: ['lstActivity', 'btnExportCsv'],
    },
    lstActivity: {
      id: 'lstActivity',
      type: 'ListBox',
      bounds: { x: 16, y: 30, width: 468, height: 160 },
      properties: {
        name: 'lstAuditEvents',
        enabled: true,
        visible: true,
        items: [
          '#1094: Пользователь ivan_k оформил заказ на сумму 14,200 ₽',
          '#1093: Оплата счета INV-2024-889 успешно подтверждена',
          '#1092: Смена пароля администратором sec_admin',
          '#1091: Экспорт финансовой ведомости в XLSX',
          '#1090: Обновление сертификата безопасности SSL',
        ],
      },
      events: { SelectedIndexChanged: 'lstAuditEvents_SelectedIndexChanged' },
      parentId: 'panelTable',
      childrenIds: [],
    },
    btnExportCsv: {
      id: 'btnExportCsv',
      type: 'Button',
      bounds: { x: 354, y: 202, width: 130, height: 32 },
      properties: {
        name: 'btnExportLog',
        text: 'Экспорт в Excel',
        enabled: true,
        visible: true,
        backColor: '#10B981',
        foreColor: '#FFFFFF',
      },
      events: { Click: 'btnExportLog_Click' },
      parentId: 'panelTable',
      childrenIds: [],
    },
  };

  return {
    version: '1.0.0',
    projectName: 'AdminDashboard',
    rootFormId: rootId,
    nodes,
    selectedNodeIds: ['panelTable'],
    targetFramework: 'WinForms',
  };
};

export const createSettingsTemplate = (): DesignerProjectState => {
  const rootId = 'form_settings';

  const nodes: Record<string, DesignerNode> = {
    [rootId]: {
      id: rootId,
      type: 'Form',
      bounds: { x: 0, y: 0, width: 520, height: 420 },
      properties: {
        name: 'SettingsDialog',
        text: 'Параметры приложения',
        enabled: true,
        visible: true,
        backColor: '#F8FAFC',
        foreColor: '#0F172A',
        fontFamily: 'Segoe UI',
        fontSize: 9,
      },
      events: {
        Load: 'SettingsDialog_Load',
      },
      parentId: null,
      childrenIds: ['tabCtrl', 'btnSaveSettings', 'btnCloseSettings'],
    },
    tabCtrl: {
      id: 'tabCtrl',
      type: 'TabControl',
      bounds: { x: 20, y: 20, width: 480, height: 330 },
      properties: {
        name: 'tabControl1',
        enabled: true,
        visible: true,
        tabTitles: ['Основные', 'Сеть & API', 'Безопасность'],
        activeTabIndex: 0,
      },
      events: {},
      parentId: rootId,
      childrenIds: ['lblLanguage', 'cmbLanguage', 'chkAutoStart', 'chkDarkTheme', 'lblCacheLimit', 'txtCacheLimit'],
    },
    lblLanguage: {
      id: 'lblLanguage',
      type: 'Label',
      bounds: { x: 40, y: 70, width: 140, height: 18 },
      properties: {
        name: 'lblLanguage',
        text: 'Язык интерфейса:',
        enabled: true,
        visible: true,
        fontBold: true,
      },
      events: {},
      parentId: 'tabCtrl',
      childrenIds: [],
    },
    cmbLanguage: {
      id: 'cmbLanguage',
      type: 'ComboBox',
      bounds: { x: 40, y: 95, width: 220, height: 32 },
      properties: {
        name: 'cmbLanguage',
        text: 'Русский (RU-ru)',
        enabled: true,
        visible: true,
        items: ['Русский (RU-ru)', 'English (US-en)', 'Deutsch (DE-de)', 'Français (FR-fr)'],
      },
      events: { SelectedIndexChanged: 'cmbLanguage_SelectedIndexChanged' },
      parentId: 'tabCtrl',
      childrenIds: [],
    },
    chkAutoStart: {
      id: 'chkAutoStart',
      type: 'CheckBox',
      bounds: { x: 40, y: 145, width: 260, height: 24 },
      properties: {
        name: 'chkAutoStart',
        text: 'Автозапуск вместе с Windows',
        enabled: true,
        visible: true,
        checked: true,
      },
      events: {},
      parentId: 'tabCtrl',
      childrenIds: [],
    },
    chkDarkTheme: {
      id: 'chkDarkTheme',
      type: 'CheckBox',
      bounds: { x: 40, y: 180, width: 260, height: 24 },
      properties: {
        name: 'chkDarkTheme',
        text: 'Использовать темную тему (Dark Mode)',
        enabled: true,
        visible: true,
        checked: false,
      },
      events: {},
      parentId: 'tabCtrl',
      childrenIds: [],
    },
    lblCacheLimit: {
      id: 'lblCacheLimit',
      type: 'Label',
      bounds: { x: 40, y: 225, width: 180, height: 18 },
      properties: {
        name: 'lblCacheLimit',
        text: 'Лимит дискового кэша (МБ):',
        enabled: true,
        visible: true,
        fontBold: true,
      },
      events: {},
      parentId: 'tabCtrl',
      childrenIds: [],
    },
    txtCacheLimit: {
      id: 'txtCacheLimit',
      type: 'TextBox',
      bounds: { x: 40, y: 248, width: 140, height: 32 },
      properties: {
        name: 'txtCacheLimit',
        text: '1024',
        enabled: true,
        visible: true,
      },
      events: {},
      parentId: 'tabCtrl',
      childrenIds: [],
    },
    btnSaveSettings: {
      id: 'btnSaveSettings',
      type: 'Button',
      bounds: { x: 280, y: 365, width: 120, height: 36 },
      properties: {
        name: 'btnSave',
        text: 'Применить',
        enabled: true,
        visible: true,
        backColor: '#2563EB',
        foreColor: '#FFFFFF',
        fontBold: true,
      },
      events: { Click: 'btnSave_Click' },
      parentId: rootId,
      childrenIds: [],
    },
    btnCloseSettings: {
      id: 'btnCloseSettings',
      type: 'Button',
      bounds: { x: 410, y: 365, width: 90, height: 36 },
      properties: {
        name: 'btnCancel',
        text: 'Закрыть',
        enabled: true,
        visible: true,
        backColor: '#E2E8F0',
        foreColor: '#1E293B',
      },
      events: { Click: 'btnCancel_Click' },
      parentId: rootId,
      childrenIds: [],
    },
  };

  return {
    version: '1.0.0',
    projectName: 'SettingsModule',
    rootFormId: rootId,
    nodes,
    selectedNodeIds: ['tabCtrl'],
    targetFramework: 'WinForms',
  };
};

/**
 * Multi-Form Stacking Context Template
 * Creates Form1 (Main Dashboard with Win11 Mica) and Form2 (LoginForm with Linux GTK)
 */
export const createMultiFormTemplate = (): DesignerProjectState => {
  const form1Id = 'form_main';
  const form2Id = 'form_login';

  const nodes: Record<string, DesignerNode> = {
    // FORM 1: Main Dashboard (Windows 11 Mica Skin)
    [form1Id]: {
      id: form1Id,
      type: 'Form',
      bounds: { x: 30, y: 30, width: 620, height: 420 },
      properties: {
        name: 'Form1',
        text: 'Main Dashboard',
        enabled: true,
        visible: true,
        backColor: '#FFFFFF',
        foreColor: '#0F172A',
        fontFamily: 'Segoe UI',
        fontSize: 9,
        customProps: {
          themeOverride: 'Win11Mica',
          isMainWindow: true,
        },
      },
      events: { Load: 'Form1_Load' },
      parentId: null,
      childrenIds: ['lblForm1Title', 'lblNumA', 'txtNumA', 'lblNumB', 'txtNumB', 'btnCalculate', 'btnSubmitMain'],
    },
    lblForm1Title: {
      id: 'lblForm1Title',
      type: 'Label',
      bounds: { x: 30, y: 25, width: 300, height: 26 },
      properties: {
        name: 'lblDashboard',
        text: 'Панель управления системой',
        enabled: true,
        visible: true,
        fontSize: 13,
        fontBold: true,
        foreColor: '#0F172A',
      },
      events: {},
      parentId: form1Id,
      childrenIds: [],
    },
    lblNumA: {
      id: 'lblNumA',
      type: 'Label',
      bounds: { x: 30, y: 70, width: 90, height: 20 },
      properties: {
        name: 'lblNumA',
        text: 'Число A:',
        enabled: true,
        visible: true,
        fontSize: 9,
      },
      events: {},
      parentId: form1Id,
      childrenIds: [],
    },
    txtNumA: {
      id: 'txtNumA',
      type: 'TextBox',
      bounds: { x: 125, y: 66, width: 140, height: 28 },
      properties: {
        name: 'txtNumA',
        text: '150',
        enabled: true,
        visible: true,
      },
      events: {},
      parentId: form1Id,
      childrenIds: [],
    },
    lblNumB: {
      id: 'lblNumB',
      type: 'Label',
      bounds: { x: 30, y: 110, width: 90, height: 20 },
      properties: {
        name: 'lblNumB',
        text: 'Число B:',
        enabled: true,
        visible: true,
        fontSize: 9,
      },
      events: {},
      parentId: form1Id,
      childrenIds: [],
    },
    txtNumB: {
      id: 'txtNumB',
      type: 'TextBox',
      bounds: { x: 125, y: 106, width: 140, height: 28 },
      properties: {
        name: 'txtNumB',
        text: '50',
        enabled: true,
        visible: true,
      },
      events: {},
      parentId: form1Id,
      childrenIds: [],
    },
    btnCalculate: {
      id: 'btnCalculate',
      type: 'Button',
      bounds: { x: 30, y: 155, width: 150, height: 35 },
      properties: {
        name: 'btnCalculate',
        text: 'Рассчитать',
        enabled: true,
        visible: true,
        backColor: '#2563EB',
        foreColor: '#FFFFFF',
      },
      events: { Click: 'btnCalculate_Click' },
      parentId: form1Id,
      childrenIds: [],
    },
    btnSubmitMain: {
      id: 'btnSubmitMain',
      type: 'Button',
      bounds: { x: 195, y: 155, width: 140, height: 35 },
      properties: {
        name: 'btnSubmit',
        text: 'Отправить',
        enabled: true,
        visible: true,
        backColor: '#10B981',
        foreColor: '#FFFFFF',
      },
      events: { Click: 'btnSubmit_Click' },
      parentId: form1Id,
      childrenIds: [],
    },

    // FORM 2: Login Dialog (Linux GTK / Ubuntu Skin)
    [form2Id]: {
      id: form2Id,
      type: 'Form',
      bounds: { x: 690, y: 30, width: 440, height: 360 },
      properties: {
        name: 'LoginForm',
        text: 'LoginForm',
        enabled: true,
        visible: true,
        backColor: '#F8FAFC',
        foreColor: '#0F172A',
        fontFamily: 'Segoe UI',
        fontSize: 9,
        customProps: {
          themeOverride: 'LinuxGTK',
          isMainWindow: false,
        },
      },
      events: { Load: 'LoginForm_Load' },
      parentId: null,
      childrenIds: ['lblLoginUser', 'txtLoginUser', 'lblLoginPass', 'txtLoginPass', 'btnLogin', 'btnCancelLogin'],
    },
    lblLoginUser: {
      id: 'lblLoginUser',
      type: 'Label',
      bounds: { x: 35, y: 45, width: 80, height: 20 },
      properties: {
        name: 'lblUser',
        text: 'Логин:',
        enabled: true,
        visible: true,
        fontSize: 9,
      },
      events: {},
      parentId: form2Id,
      childrenIds: [],
    },
    txtLoginUser: {
      id: 'txtLoginUser',
      type: 'TextBox',
      bounds: { x: 120, y: 41, width: 260, height: 28 },
      properties: {
        name: 'txtUser',
        text: 'admin',
        enabled: true,
        visible: true,
      },
      events: {},
      parentId: form2Id,
      childrenIds: [],
    },
    lblLoginPass: {
      id: 'lblLoginPass',
      type: 'Label',
      bounds: { x: 35, y: 90, width: 80, height: 20 },
      properties: {
        name: 'lblPass',
        text: 'Пароль:',
        enabled: true,
        visible: true,
        fontSize: 9,
      },
      events: {},
      parentId: form2Id,
      childrenIds: [],
    },
    txtLoginPass: {
      id: 'txtLoginPass',
      type: 'TextBox',
      bounds: { x: 120, y: 86, width: 260, height: 28 },
      properties: {
        name: 'txtPass',
        text: '••••••••',
        enabled: true,
        visible: true,
      },
      events: {},
      parentId: form2Id,
      childrenIds: [],
    },
    btnLogin: {
      id: 'btnLogin',
      type: 'Button',
      bounds: { x: 120, y: 150, width: 120, height: 35 },
      properties: {
        name: 'btnLogin',
        text: 'Войти',
        enabled: true,
        visible: true,
        backColor: '#E95420', // Ubuntu Orange
        foreColor: '#FFFFFF',
      },
      events: { Click: 'btnLogin_Click' },
      parentId: form2Id,
      childrenIds: [],
    },
    btnCancelLogin: {
      id: 'btnCancelLogin',
      type: 'Button',
      bounds: { x: 255, y: 150, width: 120, height: 35 },
      properties: {
        name: 'btnCancel',
        text: 'Отмена',
        enabled: true,
        visible: true,
        backColor: '#E2E8F0',
        foreColor: '#1E293B',
      },
      events: { Click: 'btnCancel_Click' },
      parentId: form2Id,
      childrenIds: [],
    },
  };

  return {
    version: '1.0.0',
    projectName: 'MultiFormStudio',
    rootFormId: form1Id,
    activeFormId: form1Id,
    formIds: [form1Id, form2Id],
    canvasSettings: {
      gridStep: 8,
      snapToGrid: true,
      globalTheme: 'Win11Mica',
      showGrid: true,
    },
    nodes,
    selectedNodeIds: ['btnSubmitMain'],
    targetFramework: 'WinForms',
  };
};
